### ISSUE TITLE
GitHub Migration Plan 

### ISSUE THREAD

**Issue by dblodgett-usgs** [cf-convention/cf-conventions#106]
Dear All,

@rsignell-usgs has urged me to comment on the [thread related to GitHub and it’s use in place of trac](https://cf-trac.llnl.gov/trac/ticket/160#comment:11). I don’t have a trac account and couldn’t figure out how to sign up, so I've decided to respond in github to demonstrate what it's about.

As someone who uses GitHub extensively for project planning/management, as a source code repository, and as a registry for development of an in-process OGC standard, I don’t think it’s worth debating the merits of github’s community facilitation model. Rather, the discussion should be how this community wants to migrate its existing activities to GitHub and how the community wants to leverage the github infrastructure. 

A few points to note about github's functionality that may be of use to the community. 

1. The CF email list should probably live on near term, at some level, and repeating GitHub notifications through the list is fine. That said, this is the last email list I’m on and I REALLY wish it would move to a searchable indexed list of issues, as I’d like to get the conversations out in the open and not buried in email formatting and archived inboxes.  [Subscribing is really easy!](https://help.github.com/articles/watching-repositories/) [Joining github is too!](https://github.com/join)
2. [Github issues](https://guides.github.com/features/issues/) work just like email if you want to use them that way. Once you’ve [watched a repository](https://help.github.com/articles/watching-repositories/), you [can respond directly](https://github.com/blog/811-reply-to-comments-from-email) to an issue email and your comment shows up in the issue’s discussion.
3. Using GitHub is easy if you don’t care to use all the software repository features, e.g. branches. [There’s super simple wiki functionality,](https://guides.github.com/features/wikis/) [forking a project](https://guides.github.com/activities/forking/) and [editing documents in the browser](https://github.com/blog/844-forking-with-the-edit-button) are super simple and you don’t need to know all the complexities behind it.
4. A lot more cool stuff can be done... and things can get kind of out of hand... [peruse the back issues here](https://github.com/twhiteaker/netCDF-CF-simple-geometry/issues) or [just check out this cherry bomb of a 60-comment thread!](https://github.com/twhiteaker/netCDF-CF-simple-geometry/issues/40)

On and on... Like I said above though, the discussion should be how does the community want ot use this system. What the tagging scheme will be, things like repository ownership raised by @marqh in #63, how to deal with stale old pull requests like #35, etc. etc.

Finally, regarding sequencing, I hope we could get 1.7 done and dusted prior to suggesting a full stop change to the infrastructure underlying CF governance. It would make a lot of sense to move 1.7+ into the new space though.

Regards, 

Dave

p.s. It's always good practice to finish a new issue with closure criteria so it's original intent is clear. This issue can be closed once a planning of a process to decide how the community wants to use github has started.

**Comment by painter1** [comment]
I would like to see a move to Github for specific issues, but I think a mailing list is more convenient for unstructured discussions.  I see no reason to stick with Trac for issue tracking, although the transition between issue trackers will take some time.

To sign up for the Trac issue tracker, email me!  Instructions are in large blue letters on the bottom of every page.  Registration used to be automated but then we got spam.  This was the surest way I could see to avoid spam on Trac.

Finally, version 1.7 of the CF Conventions document is well along now.  The conformance document will follow.

**Comment by dblodgett-usgs** [comment]
:+1: to keeping the mailing list for now. I really think the ability to cross reference, search for, tag, etc. issues instead of having free-form email could be advantageous in the long run though. 

As an FYI, I responded to this via my email. 

Also, note that there is a “mute the thread” link at the bottom of every GitHub notification as well as a “view it on GitHub” link. These are very convenient.

**Comment by dblodgett-usgs** [comment]
Where do we stand on this? The cf email list has been pretty quiet, but this space has been even quieter. @painter1 -- did the tests over in #126 work out?

**Comment by dblodgett-usgs** [comment]
Great! Then I think my closure criteria are satisfied. I'll go ahead and close this.
