### ISSUE TITLE
Typos in Appendix H

### ISSUE THREAD

**Issue by painter1** [cf-convention/cf-conventions#110]
Charlie Zender noticed some anomalies in Appendix H, section H.6.3.  He saw them in version 1.7, but they have been around for some time.  I will fix them.  Here is his email on the cf-metadata list:

These appear to be typos near the end of the current 1.7 draft:

1. 'projectory' should be 'trajectory'
2. omit 'section = 3;'
3. 'section:standard_namecf_role = "trajectory_id" ;' should be 'cf_role = "trajectory_id" ;'

**Comment by czender** [comment]
just adding myself to this thread...

**Comment by painter1** [comment]
The typo corrections have been merged into the master branch and will be part of the CF Conventions version 1.7.
