### ISSUE TITLE
Suggested corrections in "OGC WKT Coordinate System Issues" wiki page

### ISSUE THREAD

**Issue by desruisseaux** [cf-convention/cf-conventions#124]
The [OGC WKT Coordinate System Issues](https://github.com/cf-convention/cf-conventions/wiki/OGC-WKT-Coordinate-System-Issues) page is slightly outdated (it said nothing about ISO 19162, a.k.a. "WKT 2") and sometime inexact (in the line _"While this text clearly has an error in it"_, the original author seems to have missed that the `GEOGCS` and `GEOCCS` are not the same WKT element). I can volunteer for editing this page with the following content:

* Add ISO 19162 in the discussion.
* Fix the confusion in the paragraph about `PRIMEM` units.
* The paragraph about `TOWGS84` become irrelevant in WKT 2. While we should keep this discussion for historical purpose, I suggest to add a paragraph explaining why `TOWGS84` is deprecated and not supported anymore in WKT 2.

Is there any objection if I edit the wiki page accordingly?

**Comment by JonathanGregory** [comment]
Dear Martin
Thanks for checking this and volunteering to correct it. We haven't yet quite sorted out how to use GitHub issues for discussing proposed changes to the convention, so please could you repost your comment above to a new trac ticket at https://cf-trac.llnl.gov? If you don't have a trac account, painter1@llnl.gov can help.
Best wishes
Jonathan

**Comment by desruisseaux** [comment]
Hello Jonathan. Thanks for the reply. I didn't found an issue tracker on https://cf-trac.llnl.gov - only a list of projects (AIMS, ACME, CDP, DREAM, ESGF, PCMDI, UV-CDAT). It is not clear to me which project applies to CF-conventions. Or are additional links expected to appear for peoples having a track account?

**Comment by JonathanGregory** [comment]
Dear Martin

Sorry, I didn't realise that wasn't the complete URL needed. Please try
https://cf-trac.llnl.gov/trac instead.

Best wishes

Jonathan

**Comment by painter1** [comment]
We had a little problem which has been fixed.  cf-trac.llnl.gov is supposed to be a little web page where you click to get the real web site, cf-trac.llnl.gov/trac.   It's been restored to the right page.

Why doesn't cf-trac.llnl.gov give you the Trac site directly?  Because the cf-trac.llnl.gov server is shared with other web sites, this was a quick, easy, and safe way to set it up.

**Comment by desruisseaux** [comment]
Hello, sorry for the very late answer (had a long, long rush at work). I can see https://cf-trac.llnl.gov/trac/query but can not see how to create a new issue. I presume that I need to login, but don't see where to create an account.

Note that the "OGC WKT Coordinate System Issues" page seems to be editable by any GitHub user - I'm not sure it is the intend, but it appears that I could edit that page directly. Should the write access be restricted?

**Comment by JonathanGregory** [comment]
Jeff can give you a trac account.

**Comment by desruisseaux** [comment]
How can I contact Jeff? Did I missed a "contact" link on the issue tracker?

**Comment by taylor13** [comment]
perhaps a ping here will work:  @painter1 , please see above.

**Comment by JonathanGregory** [comment]
Dear Martin

I though it was on the trac website. He is painter1@llnl.gov.

Best wishes

Jonathan

**Comment by dblodgett-usgs** [comment]
Was this issue resolved over on trac? Might I suggest that if we can't get trac to work, we just move our discourse to github?

**Comment by cf-metadata-list** [comment]
Dear Martin

There is an intention to move to GitHub, but not yet a plan - I'm going to post
again to the trac ticket soon about that matter. So please proceed with trac
for the moment.

Best wishes

Jonathan

**Comment by desruisseaux** [comment]
Done: https://cf-trac.llnl.gov/trac/ticket/172

**Comment by dblodgett-usgs** [comment]
This is recorded and fixed here: https://github.com/cf-convention/cf-conventions/wiki/OGC-WKT-Coordinate-System-Issues
