### ISSUE TITLE
test

### ISSUE THREAD

**Issue by painter1** [cf-convention/cf-conventions#126]
Please ignore this.

**Comment by painter1** [comment]
Please ignore this too.

**Comment by painter1** [comment]
Please ignore this test.

**Comment by painter1** [comment]
Testing, please ignore.

**Comment by painter1** [comment]
Please ignore this test.

**Comment by painter1** [comment]
This should be the last test you see; please ignore this too.

**Comment by painter1** [comment]
Please ignore this test.

**Comment by painter1** [comment]
Please ignore this test.

**Comment by cf-metadata-list** [comment]
I'm sorry about the recent test emails.  I had planned a less intrusive way to set up the connection between our CF Conventions issue tracker on Github, and this mailing list.  It wasn't working.  If you get this message, then this simpler connection is working.
- Jeff Painter
