### ISSUE TITLE
Review repository "labels"

### ISSUE THREAD

**Issue by dblodgett-usgs** [cf-convention/cf-conventions#131]
The [labels](https://github.com/cf-convention/cf-conventions/labels) list is good but could use some modifications? 

![screen shot 2018-06-07 at 7 19 46 am](https://user-images.githubusercontent.com/1492803/41099132-3225bb0c-6a23-11e8-9b73-ae6a88e04d5e.png)

Suggestion:
Remove: `asciidoctor mod?`, `bug`, `invalid`, `simple`. 
Add: `typo`, `style`

This issue is related to #130

**Comment by ChrisBarker-NOAA** [comment]
+! I was just thinking that asciidoctor mod should be replaced by something bout style. So perfect.

:-)

**Comment by dblodgett-usgs** [comment]
updated the labels
