### ISSUE TITLE
Place CF, UGRID and SGRID docs on ftp://ftp.unidata.ucar.edu/pub/netcdf/Conventions

### ISSUE THREAD

**Issue by rsignell-usgs** [cf-convention/cf-conventions#154]
In the CF conventions document [section 2.6.1](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#identification-of-conventions) it says:

> The conventions directory name is currently interpreted relative to the directory pub/netcdf/Conventions/ on the host machine ftp.unidata.ucar.edu

This does not seem to be the case however.   Looking at ftp://ftp.unidata.ucar.edu/pub/netcdf/Conventions, we do not see CF:
![2018-12-14_8-44-49](https://user-images.githubusercontent.com/1872600/50007180-1babb480-ff7e-11e8-9784-0e17771b10ca.png)
   

We should put CF, UGRID and SGRID there as additional conventions.

This clearly needs to be done by a Unidata person.  

@ethanrd, can you make this happen?

**Comment by dopplershift** [comment]
Might be a good time to find a better hosting solution for 2018 (soon 2019) rather than FTP...is there any reason these kinds of things shouldn't just be hosted on an actual web server?

**Comment by ethanrd** [comment]
@rsignell-usgs - The README file in that directory says that

> The web page
> 
>   http://www.unidata.ucar.edu/software/netcdf/conventions.html
> 
> is now the preferred and authoritative location for registering a URI reference to a set of conventions maintained elsewhere. The FTP site will be preserved for compatibility with existing references, but authors of new conventions should submit a request to support-netcdf@unidata.ucar.edu for listing on this page.

UGRID and SGRID (and CF) are already on the conventions web page. So, that seems good for UGRID and SGRID. I'm not sure why CF isn't included in that ftp directory. It evidently wasn't there back in 2010 either (see the last bit in this [email](http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2010/003200.html) to the CF list).

On the other hand, the web page list of conventions doesn't lend itself to machine readability. Which I suspect might be useful for the netCDF-LinkedData effort. @jyucsiro, @marqh, any thoughts?

**Comment by rsignell-usgs** [comment]
Closing this issues because conventions.html link for `ugrid` and `sgrid` now link to functioning web pages.
