### ISSUE TITLE
Cannot assign labels to issues

### ISSUE THREAD

**Issue by twhiteaker** [cf-convention/cf-conventions#157]
CONTRIBUTING.md says to assign labels to issues, but I (and other users) don't have permission to do so, unless I'm missing something.

**Comment by dopplershift** [comment]
I think you actually need write permission on a GitHub repository to add labels.

**Comment by dblodgett-usgs** [comment]
That's a problem. I guess we'll have to rescind that guideline and say that labels should be applied by a moderator?

**Comment by twhiteaker** [comment]
I think it would be good if the issue submitter at least suggested a label.  Thinking about the right label may help them frame the issue with respect to the ways CF categorizes issues.

**Comment by zklaus** [comment]
Perhaps [issue templates](https://help.github.com/en/articles/creating-issue-templates-for-your-repository) can be of help here.

**Comment by ngalbraith** [comment]
I changed the label from defect to GitHubProblem, because I think Defect should be reserved for issues related to Defects in CF, not GitHub usage issues. Also this isn't a problem, at least if you're logged in to GitHub, so I'm tempted to close it. Are others still having a problem with labels?

**Comment by twhiteaker** [comment]
It's a defect with CONTRIBUTING.md, which says to assign labels to issues. As a contributor, I can create an issue, but I cannot assign a label to it, because I am not an official contributor to this GitHub project.  This means, potential contributors cannot follow all the steps for contributing.

I think CONTRIBUTING.md should be revised to say,

4. **Use [labels](https://github.com/cf-convention/cf-conventions/labels) on issues and pull requests.** 
Contributions must be presented as enhancements, defects, or typos and labeled accordingly.  If you do not have permission to assign labels, then please suggest an appropriate label.

**Comment by taylor13** [comment]
I just tested whether I could change the label and I could.

**Comment by twhiteaker** [comment]
I cannot assign or change labels. The gear icon is not available to me.  

![image](https://user-images.githubusercontent.com/699496/59297239-64060f80-8c4d-11e9-8ad9-df2cb7027d92.png)


> because I am not an official contributor to this GitHub project.

**Collaborator** is the term I was looking for.  If you have the right permissions, you can see who is a collaborator by going to 
https://github.com/cf-convention/cf-conventions/settings/collaboration

Otherwise, you'll get a 404 page.  I'm guessing @taylor13 is a collaborator (with write access maybe?) and I am not.

**Comment by zklaus** [comment]
I have the same issue as @twhiteaker . One way to address this could be the addition of one issue template for every issue type that should be supported by default. I drafted a template for typos here: zklaus/cf-conventions@a8f8ca37bb95956f420a4b9ed4d069e43e3cd199

If you want to see how issue templates appear to the user, you can open an issue in [my test repository](https://github.com/zklaus/test/issues). You will notice that for bug reports, even though you have no way to set the labels when you open the issue, the correct label appears.

Another advantage is that `assignees` can be named in the template, so that every issue already starts its life with an appropriate person responsible, that, of course, can reassign the issue as they see fit.

**Comment by dblodgett-usgs** [comment]
@zklaus I think your solution is pretty solid. The template is basically documentation of what the label means. 

The issue of a default assignee is interesting. Maybe there is a short list of github maintainers that would be assigned by default? 

Would you be willing to draft up the set of issue templates and open a PR? I would be happy to contribute if you get it started.

**Comment by zklaus** [comment]
I would be happy to do it, however, for you as a member of the project there is a perhaps easier way that is not available to me. If you go to https://github.com/cf-conventions/cf-conventions/issues/templates/edit you should find a special editor for issue templates. Just add some templates there and click on the `propose changes` button at the top right to either commit them directly or (better) make a new pull request.

But either way, if you prefer to go the manual route, I can draft up something. Just let me know.

**Comment by dblodgett-usgs** [comment]
I see this. I'll work something up and put it in tonight or tomorrow.

**Comment by zklaus** [comment]
I see this has been resolved by now. Maybe we can close this issue?

**Comment by twhiteaker** [comment]
I tested a template just now and it worked in assigning a label.  Hooray!
