### ISSUE TITLE
Update CONTRIBUTING to mention templates

### ISSUE THREAD

**Issue by twhiteaker** [cf-convention/cf-conventions#170]
https://github.com/cf-convention/cf-conventions/blob/master/CONTRIBUTING.md says 

> 4. Use labels on issues and pull requests. Contributions must be presented as enhancements, defects, or typos and labeled accordingly.

Once you click New Issue, you are brought to a page where you choose a template, and I think it's self-explanatory from there. Thus, I think point 4 should be removed from CONTRIBUTING.md.

**Comment by davidhassell** [comment]
I agree.
