### ISSUE TITLE
how to proceed on some issues at cfconventions.org

### ISSUE THREAD

**Issue by graybeal** [cf-convention/cf-conventions#188]
Hi everyone. My apologies in advance for creating a rather long ticket for things maybe I should probably know the answer to. Without being too meta, I'd like to know how to best proceed with a number of interrelated issues and questions.  I'll keep track of the questions with footnotes for easy referencing.

Someone asked at the ESIP SWEET breakout "is there a SWEET mapping to CF?" I eventually found documentation at http://cfconventions.org/faq.html#stdnames_grammar, but I saw one of the links was broken. [1]  Looking at a few other parts of this and related sections, I saw more suspect links, and eventually realized the whole FAQ page is kind of seriously out of date, since a lot of things have changed in CF processes. [2]  (And, major kudos to all the people contributing to the major process improvements.)

I tried to find a description of how and where to change the cfconventions.org site (just fix it? email to a list? ticket?) and things were a little ambiguous. For one, the whole site is rife with references to the Trac tickets, and various other things that are out of date. [3] For another, although the site is cfconventions.org, it's title is CF Metadata; the home page covers all things CF Conventions (conventions, standard names, metadata, tools, ...); given the site's scope, is "CF Metadata" the right title? [7]  And, I have a vague recollection of our long discussion about which of those entities are handled in which repositories/email lists, but not what was finally decided, and wasn't sure that outcome was documented anywhere (the Discussion page would be a good spot). [8] (On top of which, these issues I'm raising are about the documentation of all the above, so that's meta.)  

I did find the FAQ documentation in GitHub (https://github.com/cf-convention/cf-convention.github.io/edit/master/faq.md)—it might be nice for these pages to point to their sources with 'improve this doc' link [4]—and thought about doing a quick set of changes, but the scope was beyond my available time right now. Embarassingly, I don't know what email list covers this kind of question (http://mailman.cgd.ucar.edu/pipermail/cf-metadata seems to be about standard names?) [5], so I've resorted to this ticket to learn more.

A last question perhaps needs to be asked. I love the FAQ (perhaps because I wrote lots of it), but this will be a significant amount of work to update it. Do other people think the value proposition makes it worth the time to keep it current? [6]  (I am willing to contribute some to this, once I know the workflow, but don't think I can do a large amount any time soon.)

So, any easy recommendations/obvious answers here?

[1] link to CF-SWEET mapping in CF FAQ page broken
[2] CF FAQ page needs a thorough review and update.
[3] cfconventions.org needs thorough review and update
[4] add pointers from documentation pages to their sources in GitHub? 
[5] what is the mailing list for questions about cfconventions.org content?
[6] is it worth the time to keep the CF FAQ current?
[7] Could the cfconventions.org site benefit from a different title?
[8] is there user-facing documentation of which entities are handled in which repositories/email lists?

**Comment by davidhassell** [comment]
Hi John,

Thanks for summarizing this - here are some thoughts.

I think that the FAQ are a good resource, and we should keep them. The content is, I think, 99% good, but they do need updating for the new procedures and broken links.

Whilst we have removed Trac references and replaced them with GitHub descriptions in many places, clear there are many that have been overlooked. I shall systematically hunt them down and get them updated (via a pull request, of course).

Broken links will always plague us. I think the best way to fix them is is raise it on the mailing list and/or raise an issue at https://github.com/cf-convention/cf-convention.github.io, the repository of the web pages.

I'm not 100% sure what you mean by the title of the page being "CF Metadata". Do you mean the "CF MetaData" (capital D) that appears in the black menu bar at the top of the home page? I agree that that's iffy, and could perhaps be replaced with "Home", as that's where clicking it takes you.

The discussion page (http://cfconventions.org/discussion.html) does mention that the CF metadata mailing list can also be used for general queries,etc, but it does seem like an afterthought. To my mind, the mailing list should be billed as a general discussion channel that is also the place to discuss standard names.

**Comment by graybeal** [comment]
David, thanks for the great answers and your volunteering. Your assumption re the title was correct.

I will do tickets for some broken links after you have hunted down the systematic ones.

I wonder if the "edit it in place and then check the 'Do pull request' button" workflow works well in GitHub for simple things? Maybe I'll try on my own system...!

**Comment by JonathanGregory** [comment]
Since this question was last discussed, the broken links in the FAQ have been fixed and the CF website has been reorganised. I believe therefore that this question has been largely answered, and I will close the issue, but please feel free to ask again.
