### ISSUE TITLE
State a position on new NetCDF features not explicitly covered by the CF Conventions

### ISSUE THREAD

**Issue by MTG-Formats** [cf-convention/cf-conventions#191]
As somebody developing NetCDF 4 products using the enhanced features and trying to align to the CF Conventions, it would have helped to have have a clear position on those features not covered by the conventions. For me this was mainly the use of groups and enumerated user types. It was never clear to me if a NetCDF product with groups could be considered fully CF compliant.

I see the use of groups will be covered by the update, but I think if there are not explicit conventions for other enhancements like enumerated and other user types, then it would help to know if their use is encouraged, discouraged, banned or if there is no impact on compliance if they are used.

**Comment by JimBiardCics** [comment]
@MTG-Formats This is a contentious issue. Of course, the concept of CF compliance is not precise. There's no metric that can tell you that a given netCDF file is "80% CF compliant" or "fully CF compliant". The best you can say is that you aren't using any CF convention incorrectly. That may seem like a semantic game, but the way you look at compliance can change the way you think about the answer to your question. As an example, having attributes that are not in the CF list doesn't have any impact on CF compliance. Neither does using a scheme that depends on variables having certain names or name patterns. CF has nothing to say about them. A file that has a single file-level **`Conventions`** attribute and no other file-level or variable attribute is CF compliant. It used the one attribute correctly. It's of no benefit to anyone, but its compliant.

As near as I can tell, a file can be using some number of CF conventions correctly __and__ use groups and enumerated types, so long as the groups and enumerated types (or other new features) don't somehow violate any of the conventions being used. The issue regarding new netCDF4 features arises when a new feature collides with a convention. For example, a CF attribute such as comment is allowed at the file level and on data and coordinate variables, but if you put it on a group it is not a CF comment attribute. That doesn't make the file non-compliant, but it does make that particular instance of the attribute non-CF. An attribute such as leap_month that is declared to be numeric in [Appendix A](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#attribute-appendix) would be non-compliant if it used an enumerated type.

Others may differ with me on this, and the cf-checker app will likely complain bitterly about files with groups and such, but I don't think the conventions preclude using new features per se.

**Comment by JimBiardCics** [comment]
@dblodgett-usgs I don't think this should have been closed yet. @MTG-Formats is asking a larger question.

**Comment by dblodgett-usgs** [comment]
I migrated #192 here from the old CF2.0 repository for posterity and @MTG-Formats opened this as a new version of the same thing. I thought that was what we agreed to over in #192.

**Comment by JimBiardCics** [comment]
I misread the issue status. I think maybe I saw the __closed__ icon just before my comment and thought it meant this issue had been closed.

**Comment by JonathanGregory** [comment]
Dear Tim
I agree with Dave. To be more explicit, I would say that it is not CF-compliant to use a netCDF-4 feature as an alternative to a classic feature if the conventions document does not say this is allowed. CF-compliant applications could not be expected to recognise that as CF metadata. In the case of groups and strings we are working out change to the conventions document which describe how to use these new features in a CF-compliant way. The same could be done for other features. I think part of the case would be a convincing argument for allowing the extra complexity of doing things in an alternative way to the classic way.
Best wishes
Jonathan

**Comment by JonathanGregory** [comment]
There is not a specific proposal here, but similar questions have been asked before, so I suggest it should be addressed in the FAQ, and I am changing its label accordingly.

**Comment by ChrisBarker-NOAA** [comment]
This has a "dormant" label, but I'm not sure it is dormant. Rather it can be fully closed.

The OP wrote (in 2019):
>  For me this was mainly the use of groups and enumerated user types. 

I know groups has been addressed.

As for user defined types, 

2.2. Data Types

specifically lists the allowable types, but makes no mention of user defined types. Which is clear to me, but perhaps that should be explicitly addressed?

As for Enums -- #238 ended with a "we aren't going to support those -- at least not yet"

So I think we can remove the dormant label.
