### ISSUE TITLE
Support for enum type in CF 2.0

### ISSUE THREAD

**Issue by MTG-Formats** [cf-convention/cf-conventions#192]
CF 1.x uses an integer type with "flag_values" and "flag_meanings" attributes to create enumerated variables with self-describing flag values.

netCDF4 has added the enum type which also allows the user to create enumerated variables with self-describing flag types, but with a simpler syntax and greater re-usability. For instance, a boolean enum type may be defined once at the root level and then used consistently throughout the netCDF dataset.

Will CF 2.0 allow/support the use of the enum data type?
- Tim Patterson
  (working on netCDF formats for EUMETSAT/MTG products).

**Comment by dblodgett-usgs** [comment]
Superseded by #191 moved here for posterity.
