### ISSUE TITLE
Clarifications to use of groups

### ISSUE THREAD

**Issue by RosalynHatcher** [cf-convention/cf-conventions#203]
Following on from #144 which implemented groups, there are a couple of comments at the bottom of that issue which had been raised as a result of defining the conformance requirements for groups but have not yet implemented.  Summary of the comments and responses:

1. If paths are allowed in all areas of the convention it would be good to have a general statement that where "variable" or "dimension" is used this can either be a single variable name or a path to a variable. Perhaps we could also add path to the definitions in chapter 1? So that we don't have to define the term specifically in the conformance document.

2.  Although the CF standard doesn't standardize group names, which I understand is due to the abundance of NASA datasets that wouldn't meet this, I wonder whether it might be good to recommend that group names follow the same naming conventions as variables, dimensions and attributes (ie. begin with a letter and be composed of letters, digits and underscores). This way we would be encouraging human readable names but still allowing them not to be if required by some organizations.

Both of these were agreed in principle.

There was confirmation given that point 2 is indeed what NASA Dataset Interoperability Recommendations for Earth Science: Part 2 recommends.

**Comment by RosalynHatcher** [comment]
I'll create a PR for review.

**Comment by erget** [comment]
Hi @RosalynHatcher sorry about the long turnaround here - I'd seen this issue before and had noted down that I wanted to review the PR when it comes but haven't seen it yet.

I agree with these ideas still and would be willing to review and most likely endorse the PR :)

**Comment by RosalynHatcher** [comment]
Hi @erget sorry about the delay on this I got diverted onto something else.  I'm going to try and have a CF day tomorrow and will pick this up then.

**Comment by JonathanGregory** [comment]
@dblodgett-usgs wrote (in pull request https://github.com/cf-convention/cf-conventions/issues/203)
> With no dissent on this or #203 in a while, ok if I go ahead and merge? If no response by January 6th, I will.
Yes, please merge it. According to the rules, it's already well-qualified (in terms of time and support expressed)! Thanks for noticing.

**Comment by Dave-Allured** [comment]
Here are two technical corrections for this issue.  Both are suggested changes to **2.3. Naming Conventions**.  I am not sure whether to start a new issue, but I thought I would start here for simplicity.  I believe these are both consistent with the intentions stated above.

1.  Change this sentence as follows.
`--- This convention does not standardize any variable or dimension names.`
`+++ This convention does not standardize any variable, dimension, or group names.`

2.  Add comma to the first sentence under 2.3.  This is the famous Oxford comma, of which I am a strong believer.
`--- Variable, dimension, attribute and group names should ...`
`+++ Variable, dimension, attribute, and group names should ...`

Does anyone object?

**Comment by erget** [comment]
@Dave-Allured I don't object but as this issue has already been closed I think a new one would be better. Always a friend of the Oxford comma.
