### ISSUE TITLE
Typos in Examples H.9 to H.11 -Atmospheric sounding profiles

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/cf-conventions#210]
In the examples the temperature is given as
```
      float temperature(z) ;
          temperature:standard_name = "surface_temperature" ;
          temperature:long_name = "skin temperature" ;
          temperature:units = "Celsius" ;
          temperature:coordinates = "time lon lat z" ;
```

or

```
      float temperature(obs) ;
          temperature:standard_name = "surface_temperature" ;
          temperature:long_name = "skin temperature" ;
          temperature:units = "Celsius" ;
          temperature:coordinates = "time lon lat z" ;
```

As the temperature during the sounding is meant, in all three examples it should be

```
          temperature:standard_name = "air_temperature" ;
          temperature:long_name = "air temperature" ;
```

The unit for temperatur (if not K) should be degree_C (given in the standard-name-table column 'Canonical Units').

Additionally in H.11

```
          profile:cf_name = "profile_id";
```

is written instead of

```
          profile:cf_role = "profile_id";
```

**Comment by neumannd** [comment]
I would agree with the suggested corrections by @GeyerB (`cf_name` => `cf_role`; `air_temperature` as `standard_name`; different unit).

**Comment by JonathanGregory** [comment]
I have created [pull request 460](https://github.com/cf-convention/cf-conventions/pull/460) to make these corrections. Instead of replacing the `long_name`, I deleted it for simplicity, since it's not mandatory. Thanks for reporting the errors, @GeyerB. Please could someone check and merge. Thanks.

**Comment by larsbarring** [comment]
Thanks @GeyerB for reporting, and thanks @JonathanGregory for creating the PR, that I have just merged. Small comment: `Celsius` is in fact a valid alias for `degree_celsius`, but this does of course not matter for the PR.
