### ISSUE TITLE
Missing `s`s in grid mapping description texts

### ISSUE THREAD

**Issue by neumannd** [cf-convention/cf-conventions#213]
Several descriptions of grid mappings have attached the sentence 

> The `x` (abscissa) and `y` (ordinate) rectangular coordinates are identified by the standard_name attribute values `projection_x_coordinate` and `projection_y_coordinate` respectively.

In some sentences the _values_ is plural and in other sentences it is singular (_value_). It should be always plural. The affected sentences are in the descriptions of _Lambert Cylindrical Equal Area_, _Mercator_, _Orthographic_ and _Vertical perspective_. I will create a pull request solving this issue.

**Comment by dblodgett-usgs** [comment]
Thanks @neumannd Looks good to me and has been open long enough to merge,
