### ISSUE TITLE
Ex. 5.7 (Lambert conformal projection): changing unit of `projection_*_coordinate` from `km` to `m`

### ISSUE THREAD

**Issue by neumannd** [cf-convention/cf-conventions#215]
[Example 5.7](http://cfconventions.org/cf-conventions/cf-conventions.html#lambert-conformal-projection) shows how a Lambert conformal projection is represented. It contains two variables `x` and `y` having the `standard_name`s `projection_x_coordinate` and `projection_y_coordinate`, respectively, and the `units` `km`. However, the canonical unit of `projection_*_coordinate` is `m` (except for Geostationary projection).

Old snippet from the example:

```
  double y(y);
    y:units = "km";
    y:long_name = "y coordinate of projection";
    y:standard_name = "projection_y_coordinate";
  double x(x);
    x:units = "km";
    x:long_name = "x coordinate of projection";
    x:standard_name = "projection_x_coordinate";
```

Corrected snippet:

```
  double y(y);
    y:units = "m";
    y:long_name = "y coordinate of projection";
    y:standard_name = "projection_y_coordinate";
  double x(x);
    x:units = "m";
    x:long_name = "x coordinate of projection";
    x:standard_name = "projection_x_coordinate";
```

**Comment by taylor13** [comment]
@neumannd   By definition the units need to be consistent with, not identical to the canonical units.   To quote the convention:
```
a variable with a standard_name attribute must have units which are physically 
equivalent (not necessarily identical) to the canonical units, 
```
so "km" may be used in instead of "m".  It's up to the data writer.

**Comment by neumannd** [comment]
OK. Thanks for the info. I forgot that.
