### ISSUE TITLE
Taxon Names and Identifiers

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/cf-conventions#218]
**Title:** Taxon Names and Identifiers 
**Moderator:** @davidhassell 
**Moderator Status Review [last updated: 2019-12-02]:** Converted from accepted Trac ticket 99 to GitHub issue.
**Requirement Summary:** 
**Technical Proposal Summary:** Add support for better handling of biological taxa data
**Benefits:** 
**Status Quo:** 
**Detailed Proposal:**

### Complete proposal

The complete proposal is for a stand-alone new section (`6.1.2`), that is contained in pull request #219 

This issue was resolved as accepted in the old Trac system about a year ago, at the time of the transition to GitHUb, but didn't get converted to a pull request. This issue addresses this.

The previous discussion and evolution of this issue may be read in full at  https://cf-trac.llnl.gov/trac/ticket/99

The Trac ticket's original contributors are still happy with the proposal in it's pull request form, and therefore if there are no further comments (which would be welcome, of course! - but please read the history in Trac first), this issue can therefore be accepted after the usual three weeks.

### Consequences for Standard Names

The following new Standard Names are required to describe the label variables and to support the bacterial data request that inspired the creation of this ticket.

Note that these names have not yet been included in the standard name table, but there does not affect the enhancement issue.

`taxon_name`: The human-readable label for the taxon such as Calanus finmarchicus. The label should be registered in either WoRMS or ITIS and spelled exactly as registered.

`taxon_identifier`: The machine-readable identifier for the taxon registration in either WoRMS (the AphiaID) or ITIS (the taxonomic serial number or TSN), including namespace. The namespace strings are 'aphia:' or 'tsn:'. For example, Calanus finmarchicus is encoded as either 'aphia:104464' or 'tsn:85272'. For the marine domain WoRMS has more complete coverage and so aphia Ids are preferred.

`colony_forming_unit_number_concentration_of_taxon_in_sea_water`: "Colony Forming Unit" means an estimate of the viable bacterial or fungal numbers determined by counting colonies grown from a sample. "Number concentration" means the number of particles or other specified objects per unit volume. "Taxon" means an organism named in the taxon_name and taxon_identifier variables.

`number_concentration_of_taxon_in_sea_water`: "Number concentration" means the number of particles or other specified objects per unit volume. "Taxon" means an organism named in the taxon_name and taxon_identifier variables.

**Comment by twhiteaker** [comment]
Interesting choice using LSIDs.  My first reaction was, "CF should allow more flexibility when specifying the identifier and classification system, without forcing the user to use the LSID specification."  There's also apparently some [controversy over LSIDs](https://en.wikipedia.org/wiki/LSID#Controversy_over_the_use_of_LSIDs), and I don't now how stable the specification is.  But, the systems I typically use (WoRMS and ITIS) can be expressed with LSIDs, and I see merit in sticking with a particular convention for compatibility's sake.  So at this point I'm not suggesting a change...I'm just curious to see how it works out in practice.

FYI, my perspective is biased by [EML's recent adoption of a way of expressing taxon IDs](https://eml.ecoinformatics.org/whats-new-in-eml-2-2-0.html#support-for-ids-in-taxonomicclassification), as I've been working with EML files lately.

**Comment by roy-lowry** [comment]
Hi Tim,

The Trac ticket this is based on has been running for years. My primary motivation for proposing it was to establish taxon identifiers as a dimension so we didn't end up with a Standard Name for the abundance of every taxon in the ocean. The proposal is aimed at tagging measurements with either AphiaIDs or ITIS TSNs, which is totally in line with your thinking. 

The LSID entered the equation as the only method I could find at the outset to enable these identifiers to be encoded as URLs. There may be better ways of doing this developed in the last few years or in the future. BTW thanks for bringing the LSID URL root up to date. The way I designed things was that URL-derivation updates could be implemented as small changes to the CF Conventions text with no consequences for encoded data.

I really appreciate your making it clear that you are not requesting change in the proposal now - it's taken a lot of effort to get this far. Let's get the basic principle of establishing taxon identifiers as an auxilliary co-ordinate into CF plus the adoption of WorMS and ITIS for marking up data. Once this is established we can open a future ticket to discuss the optimal strategy for URL derivations from markup identifiers.

**Comment by davidhassell** [comment]
Thanks for these comments - it looks like we're still OK to accept this in a few days' time, if nothing further happens ...

**Comment by davidhassell** [comment]
OK - over three weeks has passed with no further comment, so we can accept this enhancement, merge the associated pull request (https://github.com/cf-convention/cf-conventions/pull/219) and close this issue.

Many thanks to all those who took part, both in the original Trac ticket and here.
