### ISSUE TITLE
Correct the wording in the conformance document section 2.3 "Naming Conventions"

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/cf-conventions#226]
**Title:** Correct the wording in the conformance document section 2.3 "Naming Conventions"

**Moderator:** @RosalynHatcher 

**Requirement Summary:** The conventions say, in section 2.3, that "Variable, dimension, attribute and group names _should_ begin with a letter, ...", but the conformance document says _must_ instead of _should_ for checking this. The Conventions document is correct (see also Trac Ticket 157 https://cf-trac.llnl.gov/trac/ticket/157), so the conformance document needs changing.

**Technical Proposal Summary:** Change "must" to "should" in that part of the conformance document, and move the whole sentence to "recommendations" (from "requirements")

**Benefits:** Everyone, as the checker will better reflect the conventions

**Status Quo:** Compliant files may fail the checks.

**Detailed Proposal:** PR to follow

**Comment by RosalynHatcher** [comment]
I agree with this and am happy with the PR.

**Comment by taylor13** [comment]
likewise, I think this correction should be made.

**Comment by DocOtak** [comment]
Should the CF conventions documentation adopt  [BCP 14](https://tools.ietf.org/html/bcp14) [[RFC2119](https://tools.ietf.org/html/rfc2119)] [[RFC8174](https://tools.ietf.org/html/rfc8174)]?

**Comment by erget** [comment]
@DocOtak I love RFC2119 and fully support using it fastidiously. It's been a great help to me in numerous requirements documents.

I do believe that migrating the document to use those terms correctly and consistently would be a larger effort that, if desired, should be a separate "project" since it's so wide-reaching.

Maybe this would be an appropriate item for the backlog to be discussed e.g. at the annual meeting and implemented as its own issue?

**Comment by davidhassell** [comment]
Using well-defined definitions for these terms sounds like a good idea, as well as, perhaps, reviewing the terms in the main conventions document. @erget's suggestions for discussing this in it's own right, as opposed to discussing it on this ticket, sounds like th right way forward, to me. Perhaps there are terms in the main conventions document that could/should be changed, too.

**Comment by davidhassell** [comment]
Merging this so that it goes in to CF-1.8. Thanks.
