### ISSUE TITLE
Add standard names for angular coordinates

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-conventions#231]
**Title:** Add standard names for angular coordinates
**Moderator:** @JimBiardCics 
**Moderator Status Review [last updated: YY/MM/DD]:** Pending
**Requirement Summary:** As discussed in #230 new standard names are needed for encoding angular coordinates.
**Technical Proposal Summary:** Add 2 new standard names to be adopted in conjunction with the changes discussed in #230 
**Benefits:** Users of angular coordinates, particularly geostationary imagery
**Status Quo:** This is discussed in #230. The `standard_name`s currently in use have canonical names that do not fulfil the needs of geostationary imagery.
**Detailed Proposal:** Add the following `standard_name`s:

| Name | Canonical units | Definition |
| ---- | --------------- | -----------|
| projection_x_angular_coordinate | radian | "x" indicates a vector component along the grid x-axis, when this is not true longitude, positive with increasing x. Angular projection coordinates are angular distances in the x- and y-directions on a plane onto which the surface of the Earth has been projected according to a map projection. The relationship between the angular projection coordinates and latitude and longitude is described by the grid_mapping. |
| projection_y_angular_coordinate | radian | "y" indicates a vector component along the grid y-axis, when this is not true latitude, positive with increasing y. Angular projection coordinates are angular distances in the x- and y-directions on a plane onto which the surface of the Earth has been projected according to a map projection. The relationship between the angular projection coordinates and latitude and longitude is described by the grid_mapping. |

A known use case is in the [geostationary projection](http://cfconventions.org/cf-conventions/cf-conventions.html#_geostationary_projection).

**Comment by JimBiardCics** [comment]
I'll moderate if you like.

**Comment by erget** [comment]
@JimBiardCics thanks for this, sorry for the slow turn-around - I'd be happy for your moderation :)

**Comment by lllliso** [comment]
I support the proposal, as erget said it is complementing: https://github.com/cf-convention/cf-conventions/issues/230.
When incorpored into the convention, it will give a coherent framework for all the geostationary satellites, that will benefit the whole community

**Comment by erget** [comment]
@lllliso thanks for providing that input - good to see this is the right track.

@JimBiardCics would you be willing to start the next steps? This is my first `standard_name` so I hope I'm not missing anything.

**Comment by japamment** [comment]
@erget @JimBiardCics I have added the proposals to the [CEDA standard names editor](http://cfeditor.ceda.ac.uk/proposals/1?status=active&namefilter=&proposerfilter=Lee&descfilter=&unitfilter=&yearfilter=&commentfilter=&filter+and+display=Filter).

The names, units and definitions look fine and I see no problem with adding them to the standard name table, assuming #230 is accepted.

**Comment by erget** [comment]
@japamment excellent, thank you very much. I've now merged #232 which closes #230 .

**Comment by feggleton** [comment]
These changes have been published in version 72 of the standard name table. - Please close this issue if all discussions are complete.

**Comment by japamment** [comment]
@feggleton thanks for publishing the names. I'm closing this issue now.
