### ISSUE TITLE
Add missing revision history entries for CF-1.8

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/cf-conventions#233]
# Title
A dd missing revision history entries for CF-1.8
# Moderator

# Requirement Summary
All merges should be accommpanied by an addition to the `history.adoc` file
# Technical Proposal Summary
Add the missing entries for the 1.8 release
# Benefits
# Status Quo
# Detailed Proposal
This should be done, I think, by the person who merges a PR, at that time, so that the history is always up to date. I shall propose a change to `CONTRIBUTING.md` to this effect in another issue.

I think it would be beneficial to stray from the rules slightly and merge the PR which address this *before* the release of 1.8 - which will be in less than 3 weeks' time. This is so that the static 1.8 document will be complete.

**Comment by erget** [comment]
You've got my support. `CONTRIBUTING.md` isn't a part of the Conventions proper either so I think that we can change this in <3w if we so choose. I would also consider changes to the history to be editorial in nature.

**Comment by davidhassell** [comment]
Thanks. I agree with the editorial nature of these thing, too. In that case, as soon as #212 is merged, we can merge the history changes as well.

**Comment by davidhassell** [comment]
Updated the history in the PR for #212 and #223. All being well, I shall merge these history changes tomorrow (and there shall be no more merges until 1.8 is released)
