### ISSUE TITLE
Add earth shape parameters to geostationary projection

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-conventions#241]
# Title
Explicitly describe earth shape parameters in Appendix F
# Moderator
@JimBiardCics 
# Moderator Status Review [last updated: YY/MM/DD]
Brief comment on current status, update periodically
# Requirement Summary
[Appendix F: Grid Mappings](http://cfconventions.org/cf-conventions/cf-conventions.html#appendix-grid-mappings) states
> The attributes which describe the ellipsoid and prime meridian may be included, when applicable, with any grid mapping.

I think this should be more specific.
# Technical Proposal Summary
Provide a list of attributes which meet these criteria.
# Benefits
Explicit is better than implicit.
# Status Quo
Currently attributes describing the ellipsoid and its prime meridian can be included in any grid mapping. This would not change, but an ambiguity would be removed.
# Detailed Proposal
As in #242

**Comment by erget** [comment]
Hello list... Is there anybody who'd be interested in moderating this proposal? It's for a very simple change: Listing explicitly what attributes are used to describe the shape of the earth and latitude/longitude coordinates in a Coordinate Reference System.

**Comment by JimBiardCics** [comment]
@erget I'll moderate.

**Comment by davidhassell** [comment]
Hi - is this just for the geostationary project, or are you proposing this for all grid mappings? Thanks.

**Comment by erget** [comment]
@JimBiardCics thanks! I've assigned you.

@davidhassell this would apply for all grid mappings "when applicable".  The details are in #242 - in essence the change would be to explicitly list what users must currently infer.

**Comment by JimBiardCics** [comment]
This proposed change is to make the generic statement
> The attributes which describe the ellipsoid and prime	the final section.
meridian may be included, when applicable, with any grid mapping.

to
> The attributes which describe the ellipsoid and prime meridian may be included, when applicable, with any grid mapping.
> These are:
> - `earth_radius`
> - `inverse_flattening`
> - `longitude_of_prime_meridian`
> - `prime_meridian_name`
> - `reference_ellipsoid_name`
> - `semi_major_axis`
> - `semi_minor_axis`

This removes any uncertainty about which attributes are being referred to.

**Comment by JimBiardCics** [comment]
As moderator I guess I can't approve of the change, so we need others to come and say so or give reason why not.

**Comment by erget** [comment]
@JimBiardCics as moderator you can express approval for the change. However, [we need at least 3 people](http://cfconventions.org/rules.html) to express support for the change, 2 of which need to be from the Conventions Committee. As it stands we're 2 for 3, but of course it might be that somebody has objections.

**Comment by erget** [comment]
...Of course that's assuming that you **would** wish to express approval - sorry for putting words in your mouth there :)

**Comment by JimBiardCics** [comment]
Ah, well then, I totally approve.

**Comment by zklaus** [comment]
For what it's worth (probably not much), I approve.

**Comment by steingod** [comment]
I also support this, although probably not worth much :-)

**Comment by erget** [comment]
Thanks! That puts us at 4/3 needed.

**Comment by JimBiardCics** [comment]
Then we'll start the countdown. Three weeks, right?

**Comment by erget** [comment]
Yes, 3 weeks, so I propose we revisit after 2020-05-05. Anybody with objections - now would be a good time to bring them to the table :)

**Comment by JonathanGregory** [comment]
This is a sensible proposal. Thanks. I support it too.

**Comment by erget** [comment]
@JimBiardCics just a gentle heads up - the 3 week period has now passed with no further objections, so IMHO this can now be merged. Do you agree, and if so would you mind merging?

**Comment by JimBiardCics** [comment]
@erget Sorry about that. I was buried under work. Thanks for doing the merge!
