### ISSUE TITLE
Clarification on x/y-grid direction in standard names

### ISSUE THREAD

**Issue by hrajagers** [cf-convention/cf-conventions#252]
There are various standard names for x- and y-components of vector quantities. For instance: `sea_water_x_velocity`. The description always states: `"x" indicates a vector component along the grid x-axis, positive with increasing x`. I assume that this description stems from the idea that the computational grid is a simple Cartesian mesh in some coordinate reference system. The attribute name `grid_mapping` also refers to that assumption.

However, in my case the curvilinear grid is not Cartesian in any coordinate system, but the grid may have been created in some local coordinate system (e.g. a UTM zone), so the grid coordinates are stored using `projection_x_coordinate` and `projection_y_coordinate` variables and the grid_mapping describes (via WKT) the relationship between those x/y coordinates and global latitude/longitude. On this curvilinear grid a `sea_water_x_velocity` quantity is stored. How should it be interpreted? As

1. a vector component along a (curvilinear) grid direction (but which one)?
2. a vector component along the `projection_x_coordinate` direction?

If 1, how should we interpret the data if it results from an unstructured model without two grid directions?
If 2, can we remove the word "grid" from the description `"x" indicates a vector component along the grid x-axis, positive with increasing x`?

Best regards,

Bert

**Comment by JimBiardCics** [comment]
@hrajagers The axis is identified on a dimension coordinate variable using the axis attribute. In your case, the X axis is the projection_x_axis.

**Comment by hrajagers** [comment]
Hi Jim,

Thank you for the reply. In your first sentence you refer to a "dimension coordinate variable" ... I can't find that exact phrase in the CF conventions document. So, I assume that you refer to a one-dimensional "coordinate variable" for which dimension name and variable name are equal such as
```
float x(x) ;
  x:standard_name = "projection_x_coordinate"
  x:axis = "X"
```
However, I don't have a one-dimensional coordinate variable. My `projection_x_coordinate` is still a two-dimensional array, so an auxiliary coordinate variable in CF terms. For example,
```
float x(m,n) ;
  x:standard_name = "projection_x_coordinate"
  x:axis = "X"
```
Do I understand it corretly that in this case the `sea_water_x_velocity` is pointing in the `projection_x_coordinate` direction?
Is it necessary (or merely recommended) to add the `axis` attribute?

Best regards,

Bert

**Comment by JimBiardCics** [comment]
@hrajagers Yes, "dimension coordinate variable" is new terminology that we are currently developing to help reduce confusion.

The axis attribute may only be applied to dimension coordinate variables (not auxiliary coordinate variables). If you don't have an actual dimension coordinate variable, you rely on the standard_name values of **`projection_x_coordinate`** and **`projection_y_coordinate`** to identify the conceptual axis directions.

Your use case definitely makes the appropriate identification difficult. This is a good example of where our use of the word "grid" can make everything more confusing. I think it would be worth a proposal to change the language.

**Comment by davidhassell** [comment]
Hi Bert and Jim,

I think that it is now permitted to have the `axis` attribute on auxiliary coordinate variables (quite buried: sixth paragraph of  http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#coordinate-system), and it can be set on N-d auxiliary coordinate variables, too. So
```
float x(m,n) ;
  x:standard_name = "projection_x_coordinate"
  x:axis = "X"
```
is OK.

My understanding(?) is that the direction "vector component along the grid x-axis" in the standard name definition is indeed assuming that there is a `1-d` dimension coordinate variable of the form `float x(x) ;`, which you do not have.

Are the component directions in your case defined as unrotated east and north? If so, then perhaps the standard_name `eastward_sea_water_velocity` is better, with the `x` and `y` auxiliary coordinate variables defined as you already have them?

Thanks,
David

**Comment by JimBiardCics** [comment]
@davidhassell I was trying to find the discussion that led to the new language about the axis attribute. I vaguely remember it, but I can't find it anywhere. Is the intent to allow application to auxiliary coordinate variables that aren't 1D?

**Comment by davidhassell** [comment]
Hi Jim,

It took me while but I think the discussion can be found have a look at http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2017/thread.html (search for threads "axis attribute"). These exchanges also  refer back to discussions in late 2006/early 2007 (same thread name). Also https://cf-trac.llnl.gov/trac/ticket/8, modified by https://cf-trac.llnl.gov/trac/ticket/62.

I've only skimmed them so far, but there is a lot of discussion on the 2-d case. I was going on memory when I said that it's OK for 2-d variables, but I shall delve deeper ....

**Comment by martinjuckes** [comment]
Hi @davidhassell : the conformance document still states that "The axis attribute is not allowed for auxiliary coordinate variables", but the CF checker appears to be updated to accept it in lien with the changes you refer to, which came into CF-1.6.

**Comment by hrajagers** [comment]
Thank you all for digging into this topic! If you all agree that the `sea_water_x_velocity` is the velocity component in the direction indicated by the `axis = X` attribute, and if that attribute can be used on an auxiliary coordinate variable (typically 2D for a curvilinear structured mesh or 1D for an unstructured mesh) then that is more or less in line with what we were hoping for. In that case, I would appreciate some guidance on -- as @JimBiardCics suggested -- how to best propose to change the language as it links to both the CF conventions document (related to the axis attribute on auxiliary coordinate variables) and the standard names table.

@davidhassell You asked whether the component directions in my case are defined as unrotated east and north? The original vector component in the numerical model are staggered and directed along the `m` and `n` dimensions of the curvilinear C-grid. The postprocessing routine transforms these vector components to co-located components along the x and y directions of the model domain which may be unrotated lat/lon (in which case we indeed write `eastward_` and `northward_sea_water_velocity`) but usually are "arbitrary" Cartesian x/y for which we can't guarantee x to be eastward and y to be northward. However, since people usually select a standardized regional CRS, in _most_ cases x will align with eastward and y with northward. So, then the question becomes ... Do I assume the alignment (and write eastward and northward components) and accept that the metadata in the NetCDF file may be incorrect when the assumption is not valid, or do I go for always correct metadata and merely indicate that the vector components are in the regional Cartesian x/y directions ... We made the latter choice, which triggers this discussion.

**Comment by neumannd** [comment]
In a current project, we have a similiar use case as @hrajagers : our projected x/y coordinates depend on two dimensions. Our wind `x_wind` and `y_wind` blows along the coordinate axes (the 1d-ones).

```
int i(i) ;
   ...
int j(j) ;
   ...
double x(j, i) ;
   x:standard_name = "projection_x_coordinate" ;
   ...
double y(j, i) ;
   y:standard_name = "projected_y_coordinate" ;
   ...
double lon(j, i) ;
   lon:standard_name = "longitude" ;
   ...
double lat(j, i) ;
   lat:standard_name = "latitude" ;
   ...
float x_wind(j, iv) ; 
   x_wind:standard_name = "x_wind" ;
   ...
float y_wind(jv, i) ;
   y_wind:standard_name = "y_wind" ;
   ...
```

I added the `i(i)` and `j(j)` variables so that the user will (hopefully) wonder if the x-wind is orientated along the axis with `...:standard_name = 'projected_x_coordinate'` or along the 1d coordinate axis. Maybe, we should also rename our variable `x` and `y`.

New standard names like `wind_along_dimension_one`, `wind_along_dimension_two`, `sea_water_velocity_along_dimension_one`, ... would be the most simple solution for clearly indicating the situation described in item (1) of the initial post of Bert.

Similarly, one could add standard names like `wind_along_coordinate_variable_one`, ... to indicate that the wind is oriented as  described in item (2) of the initial post of Bert. In addition, one needed to specify the `coordinates` attribute properly and provide the coordinate axis in _correct_ order (which is not necessary up till now).

**Comment by hrajagers** [comment]
Hi Daniel,

The reference to `dimension _one` and `dmension_two` is a bit fragile. When switching from C to FORTRAN the developer/user may easily make a mistake since the order of the dimensions would be switched. I would suggest to use a more neutral name for instance `wind_along_dimension` and add an attribute `direction_dimension = 'i'` or dimensionId in general to point to the relevant dimension.

Such an approach might also be used for vector quantities in a direction corresponding to a auxiliary coordinate variable (`direction_coordinate = 'x'`), but the earlier replies to my initial post indicate that the `axis = 'x'` attribute combined with `standard_name = 'x_wind'` is already available for that now.

Bert

**Comment by neumannd** [comment]
Hi Bert,

sorry, I miss-read your post and the one of Martin. Thanks for the clarification.

Daniel

**Comment by marqh** [comment]
> Thank you all for digging into this topic! If you all agree that the `sea_water_x_velocity` is the velocity component in the direction indicated by the `axis = X` attribute, and if that attribute can be used on an auxiliary coordinate variable (typically 2D for a curvilinear structured mesh or 1D for an unstructured mesh) then that is more or less in line with what we were hoping for. In that case, I would appreciate some guidance on -- as @JimBiardCics suggested -- how to best propose to change the language as it links to both the CF conventions document (related to the axis attribute on auxiliary coordinate variables) and the standard names table.

Some Ocean Models use a NEMO tripolar model grid in the horizontal plane.  This is not a projection. 

The is represented in netCDF with 2 2D auxiliary coordinates, providing a WGS84 latitude longitude coordinate value pair at each grid point.

The axis attribute is used to indicate the `x` and `y` and to enable quantities which are solved on grid axes to be represented.
This is deemed reasonable for this data, even though the `x` and `y` directions vary with respect to the coordinate reference system across locations in the horizontal grid.

So, I think that the methodology described here is sound and has precedent.

**Comment by JimBiardCics** [comment]
@neumannd Do your dimensional coordinate axes **`i`** and **`j`** have any physical representation?

**Comment by neumannd** [comment]
@JimBiardCics No: no physical representation. I just added them because the two wind components are oriented along these axes. The `axis` attribute should be attached to them as I learned above.

```
int i(i) ;
   i:axis = "X" ;
   ...
int j(j) ;
   j:axis = "Y" ;
   ...
```

**Comment by JimBiardCics** [comment]
How are the wind components oriented along non-physical axes?

**Comment by neumannd** [comment]
> How are the wind components oriented along non-physical axes?

Depends on the definition of a physical axis ... . The physical meaning depends on the values of  `x(i,j)` and `y(i,j)`.

* The wind flows along the grid points defined by `x(i,j)` and `y(i,j)`. `x` and `y` span up an arbitrary grid.
* `x_wind(i=a, j=b)` points from `(x(i=a, j=b), y(i=a, j=b))` to `(x(i=a+1, j=b), y(i=a+1, j=b))`.
* `y_wind(i=a, j=b)` points from `(x(i=a, j=b), y(i=a, j=b))` to `(x(i=a, j=b+1), y(i=a, j=b+1))`.

A special case would we:

If `x(i, j) = x0(i) for all i in {1, ..., I} and all j in {1, ... J}` (where we start counting with 1; where `I` and `J` are the sizes of dimensions `i` and `j`, respectively), if `y(i, j) = y0(j) for all [... as above ...]` and if `inverse_projection(x0(i), y0(j)) = (lon(i), lat(j)) with lon(i+1) > lon(i) and lat(j+1) > lat(j) for all [... as above ... except some special treatment for i=I and j=J]`, then `x_wind` would be `eastward_wind` and `y_wind` would be `northward_wind`.

**Comment by JimBiardCics** [comment]
@neumannd Thanks for taking the time to clarify.

This sounds a lot like satellite swath data. It seems to me that there must be a frame in which you have physical axes of a sort embedded in there somewhere, but if that information isn't available, it isn't. You also may not have any control over the wind component values, but it sure looks to me like the best solution would be to transform the wind vectors into the **x**/**y** frame.

It does look like your best hope is to use the axis attributes as you described above.

**Comment by neumannd** [comment]
@JimBiardCics Thanks for the feedback. Actually, its urban atmospheric model data with resolved buildings. The grid is often aligned to the building structure. Therefore, the grid orientation considerably depends on the city or district in focus. But, I just help formatting/processing the data properly and don't have any deep understanding of the topic itself ;-) .

**Comment by JonathanGregory** [comment]
I believe this question has been answered so I'm closing the issue.
