### ISSUE TITLE
PROJ.4 has advanced to PROJ v7: update Appendix F accordingly

### ISSUE THREAD

**Issue by neumannd** [cf-convention/cf-conventions#253]
# Title
PROJ.4 has advanced to PROJ v7: update Appendix F accordingly

# Moderator
@erget

# Requirement Summary
The current name of the `PROJ` package should be used which is not `PROJ.4` anymore (although `PROJ.4` was better to search for than `PROJ` ... .). URLs to external sites should work.

# Technical Proposal Summary
In Appendix F: replace `PROJ.4` by `PROJ` and update outdated URLs pointing to `http://proj4.org...`.

# Benefits
The URLs will work again. The new URLs will contain `https`. Resolve misunderstanding of new/young users who don't know PROJ.4.

# Status Quo
The `PROJ`-package is denoted as `PROJ.4` in appendix F. Most `http://proj4.org.`-URLs don't work anymore. 

# Detailed Proposal

Perform these modifications in [Appendix F: Grid Mappings](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#appendix-grid-mappings) of the CF Conventions:

* Replace `PROJ.4` by `PROJ`.
* Replace `http://proj4.org/projections/` by `https://proj.org/operations/projections/`.
* Some projections are missing a link to the corresponding description in the PROJ-manual. Add these links.

I don't think that the proposed changes will cause a controversial discussion. Therefore, I already created a pull request. Otherwise, I might forget to push it when the period for appeal of three weeks  has finished ... .

**Comment by JonathanGregory** [comment]
Thank you for proposing this, @neumannd. I agree that it's OK to classify this as a defect issue (unless anyone objects), because it doesn't change the intention of the convention, but simply corrects the conventions document. As a defect issue it will be accepted if no-one objects.

**Comment by neumannd** [comment]
Would someone be willing to moderate this issue? Three weeks without objections have passed but we are missing a moderator. Thanks in advance.

**Comment by erget** [comment]
@neumannd I'm willing to moderate this. I'll make a summary next week when back in office.

**Comment by neumannd** [comment]
@erget Thanks!

**Comment by erget** [comment]
This is a simple request to update
1. terminology referring to the PROJ.4 software, which has been renamed to PROJ
1. update links to sites that had formerly been available in the domain belonging to PROJ.4, which now must point to the new addresses used by PROJ.

The corresponding PR #254 implements these changes. These have been reviewed by @JonathanGregory and myself.

The original change request with proposed text dates back more than a month. As this is a simple fix to a defect I will merge this PR, barring objections, tomorrow.
