### ISSUE TITLE
Extend the data model for Geometries

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/cf-conventions#271]
# Title
Extend the data model for Geometries
# Moderator
@twhiteaker 

# Moderator Status Review [last updated: YY/MM/DD]
Brief comment on current status, update periodically
# Requirement Summary

The inclusion of geometry cells in CF-1.8 (http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#geometries) extended considerably the notion of cell bounds, allowing different cells to have different numbers of vertices (or "nodes") and for an individual cell to comprise a collection of multiple parts, some of which may be parts to be not included. It also allows for cell bounds to exist without a representative coordinate value.

These extra features can not be described with the existing CF data model (http://cfconventions.org/cf-conventions/cf-conventions.html#appendix-CF-data-model), but the new functionality is most definitely an _extension_ of pre-CF-1.8 cell bounds, so the data model may be extended in a backwards compatible manner. 

# Technical Proposal Summary

The new text describes _all_ coordinates in the new, more general sense, because the pre-CF-1.8 coordinate bounds are in fact special cases of the more general geometries capability.

This throws up some text that is possibly surprising at first glance, such as 
```
The bounds array spans the
domain axis constructs of the coordinate construct, with the addition
of two trailing ragged dimensions. The first extra dimension indexes
the parts of each cell and the second indexes the points that describe
each part.
```
The above statement is true for _all_ coordinate cells, so is appropriate for the data model description, but for non-geometry bounds the first ragged dimension mentioned always has size 1 and the second ragged dimension has the same length for every value (i.e. is not really ragged at all).  Note that the data model does not mandate that a software implementation has to employ these two ragged dimensions for all cell bounds. (For example, for non-geometry cells, the [cfdm library](https://ncas-cms.github.io/cfdm/tutorial.html#geometry-cells) uses the familiar single extra dimension for bounds storage, and for geometry cells with multiple parts expresses the second ragged dimension as a full dimension padded with missing data.)

# Benefits
The CF data model will be up date, benefiting all.
# Status Quo

# Detailed Proposal
See Pull request #270

I would like to thank @JonathanGregory and @twhiteaker for reviewing this prior to this issue being raised

**Comment by davidhassell** [comment]
Hello,

It has been pointed out that data model images in Appendix are not appearing in the on-line latest version of the conventions (http://cfconventions.org/cf-conventions/cf-conventions.html#appendix-CF-data-model). Sorry about this!. It will clearly need fixing prior to the release of CF-1.9.but in the mean time, the images can be seen by looking at the Appendix from GitHub: https://github.com/cf-convention/cf-conventions/blob/master/appi.adoc 

To see the proposed changes with the images, section **Coordinates: dimension coordinate and auxiliary constructs**, go to https://github.com/davidhassell/cf-conventions/blob/data_model_geometries/appi.adoc

Many thanks,
David

**Comment by twhiteaker** [comment]
The [rules](http://cfconventions.org/rules.html) state after three weeks have passed without contributions, a summary is made along with a test netCDF file if one does not already exist.  When three weeks have passed with no contributions following a summary, a decision is reached.  Since the proposed change only affects the data model and not the conventions, we shall forego the requirement of providing a test netCDF file for this issue.

**Comment by twhiteaker** [comment]
I have reviewed the proposal again and support the requested changes.  It would be good if at least two members of the conventions committee also formally stated their review here.

**Comment by dblodgett-usgs** [comment]
The text scans well. I would have benefited from a stand-alone set of definitions for these and subsequent highlighting of the normative terms or maybe just highlighting of the normative terms in the text. Terms I'm thinking about are:
- Auxiliary coordinate constructs
- Dimension coordinate construct
-  Cell method constructs

---

I notice a standalone "coordinate construct" used as in  "For a given coordinate construct ..." which has me a little confused. Can you review what you really mean by construct here? I think there might be some inconsistency in use as an instance of a coordinate construct, where "coordinate construct" is a data model -- not an instance? 

Another example of this confusion is in:

> The interior ring array spans the domain axis constructs of the coordinate construct

---

I'm struggling a little bit with the casual reference to polygons as cells -- I get it and don't disagree but think the language could treat it a little more carefully.

e.g. (note there may be other instances of this)

> If a cell is composed of multiple polygon parts, an individual polygon may define an "interior ring" ...

*If a polygonal cell is composed of multiple parts, it may have holes defined by "interior ring(s) ...*

---

I think there are probably a number of opportunities to break lists that are consecutive sentences into bulleted lists for easy of reading -- but I leave that to you as the author. 

--- 

Once these comments have been address (saying no is a fine response), I am happy with the changes and don't want to stand in the way of them getting incorporated.

**Comment by davidhassell** [comment]
Hi Dave,

> The text scans well. I would have benefited from a stand-alone set of definitions for these and subsequent highlighting of the normative terms or maybe just highlighting of the normative terms in the text. Terms I'm thinking about are:
    Auxiliary coordinate constructs
    Dimension coordinate construct
    Cell method constructs

> I think there are probably a number of opportunities to break lists that are consecutive sentences into bulleted lists for easy of reading -- but I leave that to you as the author.

I think that the style of the appendix could indeed benefit from being refactored. The text was lifted more or less verbatim from various sections of the externally published paper on the data model, because that was the easy thing to do. However, now that its official home is within the CF conventions document, it should be reviewed. This is a job which is, I hope, independent of the logical content, and so I think we can attempt this at our leisure, outside of this issue. 

With regards you specific points, there are two tables in the appendix (https://github.com/cf-convention/cf-conventions/blob/master/appi.adoc#table-cf-concepts and https://github.com/cf-convention/cf-conventions/blob/master/appi.adoc#table-cf-constructs) which should go some way to towards defining the normative terms. Also, the text always relates which well-known CF-netCDF entities relate to data model constructs (e.g. "_CF-netCDF auxiliary coordinate variables and non-numeric scalar coordinate variables correspond to auxiliary coordinate constructs._")

-----

> I'm struggling a little bit with the casual reference to polygons as cells -- I get it and don't disagree but think the language could treat it a little more carefully.

How about this new text:
```
If a polygonal cell is composed of multiple parts it may have holes,
i.e. polygon regions that are to be omitted from, as opposed to
included in, the cell extent. When such holes are present an "interior
ring" array is required that records whether each polygon is to be
included or excluded from the cell, and is supplied by an interior
ring variable in CF-netCDF. ...
```
to replace the old:

_If a cell is composed of multiple polygon parts, an individual polygon may define an "interior ring", i.e. a region that is to be omitted from, as opposed to included in, the cell extent. In this case an interior ring array is required that records whether each polygon is to be included or excluded from the cell, and is supplied by an interior ring variable in CF-netCDF. ..._

(I haven't put this change into the PR, yet)

-----

>  notice a standalone "coordinate construct" used as in "For a given coordinate construct ..." which has me a little confused. Can you review what you really mean by construct here? I think there might be some inconsistency in use as an instance of a coordinate construct, where "coordinate construct" is a data model -- not an instance?

I'm afraid that I don't understand what you mean here by _"coordinate construct" is a data model_. The text says:

```The elements of the CF data model  are called "constructs"```

```it is useful to define an abstract generic coordinate construct that can be used to refer to coordinates when the their type (dimension or auxiliary coordinate construct) is not an issue```

I _think_ that the term "coordinate constructs" is used correctly in its abstract sense, and consistently, to mean either a dimension or auxiliary coordinate construct when the distinction doesn't matter (such as when saying that "coordinate constructs provide information which locate the cells of the domain").

Please let me know if that doesn't answer you point!

All the best,
David

**Comment by twhiteaker** [comment]
The [updated text](https://github.com/cf-convention/cf-conventions/pull/270/files/788f8e3bdb88824a78ca17ea8ad5b73ec6ee26b4..c4f59ed3c44f78ae62f8748bc2468fe356eec5eb) reads:

> In CF-netCDF, when a geometry container variable is present it explicitly describes the geometry type, identifies the node coordinate variables that contain the cell vertices, and references the node count variable that contains the number of parts per cell. 

The node count and part node count variables are optional in some situations. How about this:

> In CF-netCDF, when a geometry container variable is present it explicitly describes the geometry type and identifies the node coordinate variables that contain the cell vertices.  The geometry container variable also identifies a node count variable that contains the number of nodes per cell when more than one cell is present, and a part node count variable that contains the number of nodes per cell part when cells are comprised of multipart lines, multipart polygons, and polygons with holes.

**Comment by dblodgett-usgs** [comment]
@davidhassell -- I'm happy with your proposed changes. 

Regarding the coordinate construct *instance* vs coordinate construct *data model*, let me try and clarify. 

When I see:

> For a given coordinate construct ... 

I read that as there are *n* coordinate construct instances but I think what you are actually trying to say is "For one of the CF-NetCDF data model coordinate constructs ..." ?

**Comment by davidhassell** [comment]
@dblodgett-usgs I see, now, thanks, In that light I propose changing:

_For a given coordinate construct, all the parts of all the cells must be of the same one of these three
kinds, which are called "geometry types"._ 

to simply

```
All parts of all the cells must be of the same one of these three kinds,
which are called "geometry types". 
```

I have put this change, and the other changes mooted above into the latest PR commit.

@twhiteaker Thanks for new text - I have included it in the PR.

**Comment by twhiteaker** [comment]
Updates noted.  @davidhassell now lines [343](https://github.com/cf-convention/cf-conventions/pull/270/files/c4f59ed3c44f78ae62f8748bc2468fe356eec5eb..38c1f3c0eb2a512605d3bfcd341d8bdb47c0f729#diff-8e3a4dcbfb9e94c92526ee8d9e9088e2R343) and [356](https://github.com/cf-convention/cf-conventions/pull/270/files/c4f59ed3c44f78ae62f8748bc2468fe356eec5eb..38c1f3c0eb2a512605d3bfcd341d8bdb47c0f729#diff-8e3a4dcbfb9e94c92526ee8d9e9088e2R356) are redundant.

**Comment by davidhassell** [comment]
@twhiteaker Thanks - superceded text has been removed

**Comment by JonathanGregory** [comment]
I have reviewed the present text and it seems fine to me. Thank you, all.

**Comment by twhiteaker** [comment]
Three weeks have passed since the last comment on this issue regarding proposed changes to the CF data model text. The current status indicates consensus, with @dblodgett-usgs , @JonathanGregory , and @twhiteaker supporting the proposal.  If no further contributions are made within three weeks of this summary, the proposal will be accepted and the pull request will be merged.

**Comment by twhiteaker** [comment]
Three weeks have passed without further contributions.  With a status of consensus, the proposal is now accepted.  Will someone with privileges on the repo please merge the pull request and close this issue?  Thanks!

**Comment by JonathanGregory** [comment]
Done. Thank you!
