### ISSUE TITLE
Clarification of rules for positioning comment and interval in cell methods strings

### ISSUE THREAD

**Issue by martinjuckes** [cf-convention/cf-conventions#274]
One of the contributors to the CMIP6 archive has contributed data with a `cell_methods` string of the form: `area: time: mean (interval: 1 month) where sea_ice`. CF Checker 4.0.0 reports this as an error `ERROR: (7.3): Invalid syntax for cell_methods attribute`. 

The relevant paragraph of the convention, the first in [sub-section 7.3.2](http://cfconventions.org/cf-conventions/cf-conventions.html#recording-spacing-original-data), states that "To indicate more precisely how the cell method was applied, extra information may be included in parentheses () after the identification of the method." The author of the data file is interpreting the reference to "after the identification of the method" as meaning directly after `mean` in the `cell_methods` string. This is consistent with the usage of the word "method" throughout section 7.3. 

The conformance document, on the other hand, specifies that the the parentheses should come at the end of the phrase specifying the method, i.e.  `area: time: mean where sea_ice (interval: 1 month)`, and the CF Checker, as we expect, follows the conformance document.

My personal preference would be to follow the interpretation of the conformance document, provided this is consistent with the original intention of the sub-section in 7.3, but this would, I believe, require some clarification of the text, e.g. "To indicate more precisely how the cell method was applied, extra information may be included in parentheses () at the end of the phrase identifying the method."

**Comment by JonathanGregory** [comment]
The discussion of this issue indicates that it should be addressed as a defect in the conformance document, so I am changing the label accordingly.

**Comment by JonathanGregory** [comment]
Dear @martinjuckes 

Thanks for raising this issue in 2021. No objections were raised, and enough support was expressed to approve this proposal. It requires a PR to change the first sentence in Sect 7.3.2, for which you've already suggested wording. Are you able to prepare a PR?

Best wishes and thanks

Jonathan

**Comment by JonathanGregory** [comment]
Following the agreement to make this change (in January), I have prepared [PR 536](https://github.com/cf-convention/cf-conventions/pull/536) to implement a change along the lines of @martinjuckes's suggestion. The existing text is

>  To indicate more precisely how the cell method was applied, extra information may be included in parentheses () after the identification of the method. 

and the new text is

> To indicate more precisely how the cell method was applied, extra information may be included in parentheses **`( )`** at the end of the word list describing the method, after the operation and any **`where`**, **`over`** and **`within`** phrases.

I used the phrase "word list" for consistency with the conformance document, which says

> The type of the cell_methods attribute is a string whose value is one or more blank separated word lists, each with the form `dim1: [dim2: [dim3: ...]] method [where type1 [over type2]] [within|over days|years] [(comment)]`

If no concerns are raised, this change will be merged in three weeks from today, on 14th September.

**Comment by davidhassell** [comment]
Looks good to me. Thanks, Jonathan.

**Comment by taylor13** [comment]
Me too.  Thanks.

**Comment by cofinoa** [comment]
I agree with the change

**Comment by JonathanGregory** [comment]
No-one has raised concerns, and everyone who's spoken says they're happy, so I'll merge the change now. Thanks @martinjuckes for raising the issue and suggesting the solution four years ago!
