### ISSUE TITLE
Results of discussion regarding GitHub procedures

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-conventions#275]
This issue is to record the discussion that ensued around GitHub use procedures at the 2020 CF Community Meeting on 2020-06-09. I have copied it from the [plenary discussion notes](https://docs.google.com/document/d/1lGEnqGAiudC2t3LQzp7SPmVfsQUoqQUMapjvPBY-OkE/edit) and will use it to generate issues that can be closed by setting things up in GitHub or noting good practices in CONTRIBUTING.md. Apologies for the noise - normally we like 1 issue for 1 topic but I prefer to approach this in this way in order to ensure that no contributions are lost.

> - [x] Sadie Bartholomew (NCAS/Reading): What would, or have, you done in the case that an Issue gets so many comments it becomes too impractical to follow?
> - [x] [SB as above]: Is the 3 week rule rigid (& fairly precisely held)? I am wondering about times such as over Christmas etc when people might be less active such that it could be ‘easier’ to get acceptance under that part of the rule.
>     - [x] Hélène Côté (Ouranos): I think flexibility is nice as the need to reach a diversity of point of views and other communities will increase. At least the date of the end of this period should be explicit.
>     - [x] SB: I would agree (at least some) flexibility is a plus.
>     - [x] Jonathan: I think it’s OK, within the three-week period, to “object” by saying, “I need more time.” The most important thing is not the total time it took, but that the best possible consensus is achieved.
>     - [x] Hélène Côté(Ouranos): I agree.
> - [x] David Hassell (NCAS): Who would be responsible for moving the issue between columns of the project board? The proposer, the moderator, or someone else? (I like the idea, by the way.)
> - [x] Trevor Smith (Ouranos): Have you considered using the automated features for moving KanBan cards? IE: Setting a rule that once a PR is accepted, it can move to a new column. I’m not sure if you can make time-based rules, but that could help reduce the human effort needed.
>     - [x] (Trevor Smith) I also like the idea of asking contributors to add their names to History and Contributors files. We currently do this for some projects.
>     - [x] David Hassell: I too like the idea of asking the proposer to do this.
> - [x] Karl Taylor (PCMDI):  I liked the suggested technical changes for improving the process.
> - [x] Trevor Smith (Ouranos): Minor suggestion, but if you use the html commenting conventions ( `<-- Comments go here -->`) contributors won’t need to remove them when adding a new issue/PR.
> - [x] Jonathan Gregory, Daniel Lee: note moderator in history? Keep summary up to date but also post updates as comments? 6 week wait triggered by motion?
>     - [x] David Hassell: Also note proposer in history, so contribution is made specific.
> - [x] Kanban seems to have support as voiced by Trevor & Klaus - introducing it does not cause harm
> -  [x] Jonathan: To record David’s suggestion of making a comment in the issue when the summary is updated, in order that everyone will be notified, and also because the moderator’s summary is part of the discussion and needs to be recorded therein for the discussion to make sense when read subsequently

**Comment by JonathanGregory** [comment]
To record David’s suggestion of making a comment in the issue when the summary is updated, in order that everyone will be notified, and also because the moderator’s summary is part of the discussion and needs to be recorded therein for the discussion to make sense when read subsequently

**Comment by erget** [comment]
Hi @JonathanGregory , good points - I think this would best be served in CONTRIBUTING.md as it's an implementation item, not necessarily a rule. I've spawned #362 to follow this. I'm closing this issue in favour of that one, noting that they're now linked.
