### ISSUE TITLE
Add fractional units representation example

### ISSUE THREAD

**Issue by snowman2** [cf-convention/cf-conventions#277]
Follow on from: #248  

Example: `units: 0.245 m`

**Comment by davidhassell** [comment]
Hi @snowman2  - I'm not sure what is being proposed here, as such units are [not supported](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#units) ...

> The Udunits syntax that allows scale factors and offsets to be applied to a unit is not supported by this standard. The application of any scale factors or offsets to data should be indicated by the scale_factor and add_offset attributes. Use of these attributes for data packing, which is their most important application, is discussed in detail in Section 8.1, "Packed Data".

... and since #248 has been closed. Please say if I've missed something!

Thanks,
David

**Comment by snowman2** [comment]
It works with udunits: https://github.com/pyproj4/pyproj/issues/536#issuecomment-643013825
```python
>>> from cf_units import Unit
>>> u = Unit("0.5 m")
>>> u.convert(1, "m")
0.5
```

**Comment by JonathanGregory** [comment]
It is unclear whether a change is proposed here, so I will close the issue. Feel free to reopen it if there is a question or change to discuss.
