### ISSUE TITLE
Broken link to NUG Definition of Coordinate Variables

### ISSUE THREAD

**Issue by daltonkell** [cf-convention/cf-conventions#283]
Hello all,

While searching for defining characteristics of a _coordinate variable_ versus a _geospatial variable_, I found this issue. I marked it as a defect. My search also brought me to related issue #174, which seems to not have been resolved yet.

# Hyperlink to the NetCDF Users Guide (NUG) Definition of _coordinate variable_ is broken

# Technical Proposal Summary
The aforementioned broken link, 

http://www.unidata.ucar.edu/software/netcdf/docs/netcdf_data_set_components.html#coordinate_variables

should be replaced with the working link

https://www.unidata.ucar.edu/software/netcdf/documentation/NUG/_best_practices.html#bp_Conventions

# Benefits
Removal of broken link

# Status Quo

The current stable CF Document, version 1.8, [section 1.2](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#terminology) defines a _coordinate variable_ and provides a hyperlink to the NetCDF Users Guide (NUG) definition of a _coordinate variable_ in the following block:

> __coordinate variable__
> We use this term precisely as it is defined in the [NUG section on coordinate variables](http://www.unidata.ucar.edu/software/netcdf/docs/netcdf_data_set_components.html#coordinate_variables). It is a one-dimensional variable with the same name as its dimension [e.g., time(time) ], and it is defined as a numeric data type with values that are ordered monotonically. Missing values are not allowed in coordinate variables.

Said link is broken and returns a 404 error.

# Detailed Proposal
Replace broken link with working link as detailed above.

**Comment by erget** [comment]
@daltonkell thanks for pointing this out. According to the [rules for correcting errors](http://cfconventions.org/errors.html) defects such as this should be merged automatically after a proposed change if nobody objects after being given the opportunity to do so for 3 weeks.

That being said, I checked the links in your issue and don't get a 404, so I don't see what this defect would correct. Am I looking at the right part of the document ([Section 1.2](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#terminology), link in entry "coordinate variable")?

**Comment by daltonkell** [comment]
@erget Well that's a pleasant surprise! When I had submitted this issue, the link was broken on the 1.8 stable version and 1.7 version. I just checked 1.9, 1.8, and 1.7 and it seems that the Unidata link is no longer returning a 404 error, which is great news, so I'll close this one out. Thanks for the attention 👍
