### ISSUE TITLE
Example 6.1.2 not listed in list of examples

### ISSUE THREAD

**Issue by neumannd** [cf-convention/cf-conventions#284]
# Title
Example 6.1.2 not listed in list of examples

# Moderator
@user

# Requirement Summary
Example 6.1.2 is not listed in the list of examples. The example has an achor (`taxa-ex`) but the achor is not listed in `toc-extra.adoc`.

# Technical Proposal Summary
Add the anchor `taxa-ex` with number `6.1.2.` in line `41` (between `6.1.` and `6.2.`) to `toc-extra.adoc`.

# Benefits
Have  a complete list of examples.

# Status Quo
Example 6.1.2 is missing in the list of examples.

# Associated pull request

#285

# Detailed Proposal
Example 6.1.2 is not listed in the list of examples. The example has an achor (`taxa-ex`) but the achor is not listed in `toc-extra.adoc`. Add the anchor `taxa-ex` with number `6.1.2.` in line `41` (between `6.1.` and `6.2.`) to `toc-extra.adoc`.

# Question

Or should the examples be renamed? Example 6.1.2 is the only example identified by three numbers. Should I create an extra issue for this?

**Comment by davidhassell** [comment]
Thanks @neumannd  - merging this defect now (it was actually my fault  - sorry!)
