### ISSUE TITLE
Third table in section 9.3.1 list four elements but related text and other table mention three elements

### ISSUE THREAD

**Issue by neumannd** [cf-convention/cf-conventions#288]
_**Note:** Please ignore the header lines in the tables. GitHub flavored Markdown does not seem to support tables without headers._

# Title
Third table in [Section 9.3.1](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#_orthogonal_multidimensional_array_representation) list **four** elements but related text and other table mention **three** elements

# Moderator
@user

# Requirement Summary
Consistency of examples/tables/descriptions.

# Technical Proposal Summary
Remove last line of third table of [Section 9.3.1](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#_orthogonal_multidimensional_array_representation) to get this table:

| time(o1) |
|----------|
| time(o2) |
| time(o3) |

# Benefits
Consistency with text and other table.

# Status Quo

Third table looks as follows:

| time(o1) |
|----------|
| time(o2) |
| time(o3) |
| time(o4) |

# Associated pull request
#289

# Detailed Proposal

refers to [Section 9.3.1 Orthogonal multidimensional array representation](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#_orthogonal_multidimensional_array_representation)

Third table looks as follws:

| time(o1) |
|----------|
| time(o2) |
| time(o3) |
| time(o4) |

However, the text states:

> and the element coordinate axis will be one-dimensional with size 3 (for example, the time [...] coordinates that are shared by all of the timeSeries). 

and the first table looks as follows:

| (i1, o1) | (i2, o1) | (i3, o1) | (i4, o1) |
|----------|----------|----------|----------|
| (i1, o2) | (i2, o2) | (i3, o2) | (i4, o2) |
| (i1, o3) | (i2, o3) | (i3, o3) | (i4, o3) |

Hence, the third table should look as follows:

| time(o1) |
|----------|
| time(o2) |
| time(o3) |

**Comment by davidhassell** [comment]
Thanks @neumannd .This defect is clear, fixed by the PR, and more than three have passed with no comment. Therefore we can merge the fix and close the issue.
