### ISSUE TITLE
Migrate Travis build into GitHub Actions

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-conventions#297]
As discussed previously with @lesserwhirls in #295 we have the opportunity to improve the maintainability of the Conventions by migrating fully into GitHub Actions, rather than using a combination of Travis and GitHub Actions to build all relevant artefacts. @lesserwhirls has kindly agreed to implement the changes and I'm happy to moderate and assist as per the [rules](http://cfconventions.org/rules.html) - anybody else who's interested is invited to get involved!

The benefit of doing this will be that builds will take place only in one place, not on both Travis and GitHub Actions. Currently, the build process must be maintained ATM in 2 places, meaning that sometimes changes must be made to 2 files to fix issues.

# Associated pull request
None, as yet.

**Comment by lesserwhirls** [comment]
PR cf-convention/cf-conventions#335 should be good to go - just needs a review I believe.

**Comment by sadielbartholomew** [comment]
Sorry all, the delay is my fault as I offered to review #335 but haven't yet done so as it fell off my radar. I have marked down on my TODO list to review it by the end of tomorrow (after which I go on leave for a week or so, so I will definitely have it reviewed by then).
