### ISSUE TITLE
Introduce the value "surface" for the global attribute featureType

### ISSUE THREAD

**Issue by LorenzoCorgnati** [cf-convention/cf-conventions#299]
# Title
Introduce the value "surface" for the global attribute featureType. It will describe gridded data, since the values allowed do not take into account this kind of data.
# Moderator
@roy-lowry 
# Moderator Status Review [last updated: YY/MM/DD]

# Requirement Summary
In order to describe gridded data (e.g High Frequency Radar surface current data) I propose to add the value "surface" along the allowed ones (point, timeSeries, trajectory, profile, timeSeriesProfile, trajectoryProfile) for the global attribute featureType.
# Technical Proposal Summary

# Benefits
Providers and managers of gridded data will benefit of this enhancement.
# Status Quo
The allowed values (point, timeSeries, trajectory, profile, timeSeriesProfile, trajectoryProfile) for the featureType global attribute do not suit gridded data.
# Associated pull request

# Detailed Proposal
Please see above.

**Comment by roy-lowry** [comment]
Not sure I was asked to take on the role of moderator but if there are no objections I'll do it. 

CF was initially created for gridded data. The featureType attribute was added when CF was extended to deal with discrete sampling geometries. @LorenzoCorgnati is asking the question whether gridded data should be explicitly labelled through the addition of featureType='surface' or should the existing practice of implicitly indicating gridded data through the absence of a featureType attribute  continue. I feel explicit labelling is better practice, but the existing practice has the advantage of backward compatability - so much so that if explicit labelling of gridded data through the featureType attribute is added to the Conventions then I feel the existing default implicit practice would have to remain legal and understood.

Anyone any thoughts?

**Comment by JonathanGregory** [comment]
Dear @LorenzoCorgnati

`feature_Type` is defined for discrete sampling geometries. That means situations where a combination of two or more continuous dimensions has been subsampled, and thus replaced with a smaller number of dimensions that index the samples. This is what the start of section 9 of the CF convention says:

> Discrete sampling geometry datasets are characterized by a dimensionality that is lower than that of the space-time region that is sampled; discrete sampling geometries are typically "paths" through space-time.

I'm not clear exactly what you mean by "surface", but perhaps it's a horizontal surface. Gridded data on a horizontal surface has two independent dimension x and y. If these are independently sampled, meaning that there is a point for every possible combination of x and y, it's not a discrete sampling geometry, so it doesn't need a `featureType`. You can see in Table 9.1 that all the existing `featureTypes` are defined by having a particular combination of subsampled dimensions. A distinct new `featureType` would be defined in a similar way, by a combinaton of dimensions not so far represented in the table.

If the idea is to use the `featureType` to indicate that the variable *isn't* a discrete sampling geometry, as @row-lowry suggests, then something more general than `surface` would be appropriate. For example, it could be permitted to specify `featureType` as a null string, to indicate that it isn't a DSG, and that would be equivalent to omitting the attribute altogether, if others agree that there is a general need for this.

Jonathan

**Comment by roy-lowry** [comment]
@JonathanGregory I feel more comfortable with exclusion of the featureType attribute (i.e. the status quo) than having the attribute set null.

**Comment by steingod** [comment]
I agree with @roy-lowry on having NULL attributes. Given the input by @roy-lowry and @JonathanGregory above I am not sure whether this should be included or not. If included, another keyword than surface should be used, but neither coverage (which is used in many other contexts) is appropriate given the variety of data that could fit here. If to be included I think a major restructure of conventions is necessary. Although I appreciate clear statements on the nature of data which is useful for applications analysing the data (supporting such an extension), I also see the issue of backwards compatibility. However, backwards compatibility cannot always win, then we get stuck. This is however not an issue which I find important enough to challenge that position.

**Comment by JonathanGregory** [comment]
I think the status quo is fine. It is simple and clear: if there is no `featureType`, the dataset is not a DSG. It will be interesting to see whether any others advocate the need for anything more.

**Comment by LorenzoCorgnati** [comment]
Thanks to all. I understand more clearly the meaning of a discrete sampling geometry and agree with you in keeping the status quo, i.e. the absence of the featureType attribute means that the file is not based on a DSG.

**Comment by JonathanGregory** [comment]
Thanks, Lorenzo. It was useful to clarify. Jonathan

**Comment by roy-lowry** [comment]
Thanks Lorenzo. An issue well worth raising. It is only by asking these questions that we can keep CF refreshed. I'll now close both issues.
