### ISSUE TITLE
Clarify some formula terms definitions

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/cf-conventions#304]
# Clarify some formula terms definitions

# Moderator
[TBD]

# Moderator Status Review [last updated: YYYY-MM-DD]
Brief comment on current status, update periodically

# Requirement Summary

The formulas for computing non-parametric vertical coordinates are in general well defined, but  in some cases the allowed units and standard names of some of the formula terms are not stated.

It is possible to infer the units by a dimensional analysis of the formula, and to ascertain that some terms require identical units to particular other terms. However, it would be better to state these requirements explicitly to assist data providers and anyone who writes software to carry out the computation.

The changes needed are:

* For [ocean_double_sigma_coordinate](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#_ocean_double_sigma_coordinate) that `a`, `z1` and `z2`  must all have _identical_ units of (any) length (to ensure that the tanh operand is correct). 

* For [ocean_s_coordinate](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#_ocean_s_coordinate) that `a` and `b` must be dimensionless and `depth_c` must have units of length.

* For [ocean_s_coordinate_g1](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#_ocean_s_coordinate_generic_form_1) the `computed_standard_name` and standard names of `C` and `depth_c` need defining.

* For [ocean_s_coordinate_g2](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#_ocean_s_coordinate_generic_form_2) the `computed_standard_name` and standard names of `C` and `depth_c` need defining.

The last two points are brought in from https://github.com/cf-convention/discuss/issues/84

# Technical Proposal Summary

For the relevant terms, a few lines are added to [Appendix D: Parametric Vertical Coordinates](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#parametric-v-coord).

The [conformance document](https://cfconventions.org/requirements-and-recommendations.html) is updated to include a check on the units.

# Benefits
As well bringing clarity to data providers and software writers, this change will allow the CF checker to check these items.

# Status Quo
Everyone has work out what the units and standard names of these term should be, and the CF checker has no way of reporting any errors.

# Associated pull request
PR #305

# Detailed Proposal
See PR #305

**Comment by davidhassell** [comment]
I've changed my mind about "For `ocean_double_sigma_coordinate` that `a`, `z1` and `z2` must all have identical units of (any) length (to ensure that the tanh operand is correct)".

I think that it's OK for them to have different units of length (e.g. 'm' and 'km'), and it's up to the user to do any conversions. This is how it is in the rest of CF. I shall update the PR accordingly.

**Comment by taylor13** [comment]
I support these proposed changes.  @davidhassell :  do you know anyone who has actually written a file based on these coordinates?  If so, perhaps we could ask them (or anyone who is really familiar with the coordinates) to check that the CF descriptions are correct.

**Comment by davidhassell** [comment]
Thanks, @taylor13. I don't know of any such data providers for the more involved formulas (such as `ocean_double_sigma_coordinate`), and it would indeed be good to hear from those who are familiar with them. Any takers?

**Comment by davidhassell** [comment]
Hello,

Are we OK to merge this PR, do you think? The proposed changes in #305 come from a dimensional analysis resulting from writing software can create the non-parametric vertical coordinates from formula terms. We've not heard about about any checks on the correctness of the formulae themselves, but I think that that could be raised as a new issue.

Thanks

**Comment by JonathanGregory** [comment]
Yes, I think it's OK, thanks.

**Comment by taylor13** [comment]
I agree.  It's o.k.
Thanks.

**Comment by davidhassell** [comment]
Thanks @taylor13 and @JonathanGregory, I shall merge shortly (which will also close https://github.com/cf-convention/discuss/issues/84).
