### ISSUE TITLE
QST: Can grid_mapping variable be a coordinate variable?

### ISSUE THREAD

**Issue by snowman2** [cf-convention/cf-conventions#322]
http://cfconventions.org/cf-conventions/cf-conventions#grid-mappings-and-projections

> A grid mapping variable may be referenced by a data variable in order to explicitly declare the coordinate reference system (CRS) used for the horizontal spatial coordinate values.

If you have a dimensionless variable `spatial_ref` for your `grid_mapping` variable.

```
	int64 spatial_ref ;
		spatial_ref:crs_wkt = "GEOGCRS
                ...
```
Example 1: Valid variable referencing grid mapping variable
```
	double green(time, y, x) ;
                ...
		green:grid_mapping = "spatial_ref" ;
```
Example 2: Variable referencing grid mapping variable with it also listed in the coordinate attribute:

```
	double green(time, y, x) ;
                ...
		green:coordinates = "spatial_ref" ;
		green:grid_mapping = "spatial_ref" ;
```

If 2 is not valid, why is it not valid?

**Comment by sethmcg** [comment]
2 is not valid.  The `coordinates` attribute should reference variables that give actual coordinate values for the data variable, not information about the coordinate system.  

For examples, the most common contents of the `coordinates` attribute that I've run across are references to 2-dimensional latitude and longitude arrays for data using a projected coordinate system, and references to a scalar variable indicating the height of a 2-D variable.

**Comment by snowman2** [comment]
Thanks for your response @sethmcg :+1:
