### ISSUE TITLE
Update data model figures for the Domain, and provide new image creation source code

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/cf-conventions#323]
# Update data model figures for the Domain,variable and Domain construct; and provide new image creation source code.

# Moderator
@user
# Moderator Status Review [last updated: YYYY-MM-DD]

# Requirement Summary

* The data model figures need to include the recent data model changes - i.e. the new Domain data model construct (see #301).
* The images need to be editable by the community to more easily allow future data model changes to be visualized.

# Technical Proposal Summary

The original figures, that were created with proprietary software, have been recast with [Graphviz](https://graphviz.org) - open source graph visualization software. Graphviz is, to my mind, somewhat like LaTeX in that the image is defined with human-readable text that is then rendered to an image as the software sees fit ([here is a nice "hello world" example](https://graphviz.org/Gallery/directed/hello.html)).

Other than including the new Domain variable and Domain construct, the logical content has not been changed.

# Benefits
The data model will correctly reflect the conventions.

# Status Quo
The data model description is wrong.

# Associated pull request
#324 
# Detailed Proposal
#324

**Comment by JonathanGregory** [comment]
Dear @davidhassell 

I have looked through the textual changes. I notice that "global file attribute" has changed to "group attribute". I appreciate that this is a generalisation. Is it stated somewhere that "group attribute" should be understood  to cover "global file attribute" as well?

Jonathan

**Comment by davidhassell** [comment]
Dear @JonathanGregory,

Thanks for spotting this. It is not stated that this is, as you say, a generalization. The notion of "global attributes" is still used in relation to the `featureType` attribute.

Does this improve things?

_OLD_  
"The properties of the field construct correspond to some netCDF attributes of variables (e.g. the `units`, `long_name`, and `standard_name`), and some netCDF group attributes, including (e.g. `history` and `institution`"

_NEW_  
"The properties of the field construct correspond to some netCDF attributes of variables (e.g. the `units`, `long_name`, and `standard_name`)**;** and some netCDF group attributes, **which include global attributes in the root group, such as `history` and `institution`.**"

**Comment by JonathanGregory** [comment]
Yes, that is fine - thanks, @davidhassell.

**Comment by davidhassell** [comment]
Hello - There have been no further comments for a while - is this good to be merged?
Thanks,
David

**Comment by JonathanGregory** [comment]
Since this is an enhancement, it requires the support of another committee member to satisfy the rules. Could someone else please check it?

**Comment by JonathanGregory** [comment]
In case other committee members are reading this in email without the context, perhaps it's useful to advertise that this change looks bigger than it really is. It affects Appendix I, which describes the CF data model. It is mostly concerned with the figures, which appear as large textual changes in GitHub because they are svg files, but you only have to look at them as pictures! The most useful view is the ["rich diff" of Appendix I](https://github.com/cf-convention/cf-conventions/pull/324/files?short_path=84395ff#diff-84395ffc95113b0c4c0cd22056e9b7461dc81bec9c89422b66c7b14f73d6c788). There are actually very few changes of substance.

Would suit someone who'd like to have a look at the CF data model! :smile: 

Jonathan

**Comment by dblodgett-usgs** [comment]
All looks good to me. The new figures and inclusion of source code is 👍 !!

**Comment by JonathanGregory** [comment]
Thanks for reviewing, Dave @dblodgett-usgs. I think you're right that history.adoc has not been updated yet.

**Comment by taylor13** [comment]
Yes, thanks for your prompt review.  Much appreciated since I wouldn't be able to get to it for some time.

**Comment by davidhassell** [comment]
Thanks Dave, Jonathan and Karl. I'll update `history.adoc`, and unless anything else crops up we can merge this in two weeks.

David
