### ISSUE TITLE
Conventions release dates are missing since CF-1.7 

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/cf-conventions#329]
# Conventions release dates are missing since CF-1.7 

# Moderator
@erget

# Requirement Summary

Recent versions of CF do not state their release date. This is useful information for curators, creators and for the building of other standards which rely on CF.

Since CF-1.7, the release date has been missing from the conventions document. CF-1.6 records this after the author list ([version 1.6, 5 December, 2011](https://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html)). Versions [1.7](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html), [1.8](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html) and [1.9 (draft)](https://cfconventions.org/cf-conventions/cf-conventions.html) state the version but not the release date.

All of these versions have a "Last modified" date at the very end of the document, but this may be later these date (e.g. in [1.6](https://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html)).

The "tag" dates of the versions are available at https://github.com/cf-convention/cf-conventions, but these are at a remove  from the actual published documents.

# Technical Proposal Summary
The release date is re-instated after the version in the [cf-conventions.adoc](https://raw.githubusercontent.com/cf-convention/cf-conventions/master/cf-conventions.adoc), replacing "(draft)" and following [the same pattern as CF-1.6](https://raw.githubusercontent.com/cf-convention/cf-conventions/v1.6.0/cf-conventions.adoc). This would be done by the releaser at release time.

It would be good to also add the dates to versions 1.7 and 1.8, but I'm not sure how to implement this with respect to the tagged commits in the repository.

# Benefits

Anyone who would like to know when a version of CF was released

# Status Quo
The release date is not generally known.

# Associated pull request

# Detailed Proposal

**Comment by erget** [comment]
@davidhassell I think this is a good idea and am happy to moderate.

**Comment by JonathanGregory** [comment]
I too agree with @davidhassell's proposal. I don't know how to deal with it in the GitHub repository but I don't think we should be prevented from editing past versions when (like this) it doesn't alter the convention.

**Comment by erget** [comment]
@JonathanGregory my preference would be to leave the past documents unchanged for the sake of immutability and simply include the dates in future versions. Alternatively, we could release corrections to each of the previous version that are missing the dates, i.e. 1.6.1, 1.7.1, 1.8.1, and from 1.9 forward it would be integrated into the "main line" of documents. @davidhassell what do you think?

**Comment by zklaus** [comment]
I second what @erget said. In terms of implementation of "bugfix" versions like 1.6.1, 1.7.1, etc., the github way of doing this, would be to create a branch, usually, something like v1.6.x from the commit in the history that is the release 1.6, make the changes in that branch and tag the corrected version there as v1.6.1. The branch continues to exist in perpetuity and if any more bugfix releases therein are necessary they will follow in that same branch and be tagged v1.6.2, etc. One would probably not commit to maintaining more than two major versions back, i.e. we *would* release 1.7.1 and 1.8.1, but *not* 1.6.1 since 1.6 would be considered end-of-lifed.

**Comment by davidhassell** [comment]
Thanks, all. I would probably go for the "leave the past documents unchanged for the sake of immutability and simply include the dates in future versions" at this time. 

If we wanted to do something different in the future, the approach of making a 1.7.1 branch from the 1.7.0 tag sounds very sensible.

**Comment by JonathanGregory** [comment]
I think that adding a date to an existing document is not a material change. It is a harmless alteration which makes the document more useful, and I would argue that utility is more important than the immutability of published documents. However, I don't feel strongly about it. An alternative would be to state the date next to each edition on [the web page of versions of the document](http://cfconventions.org/documents.html). Jonathan

**Comment by erget** [comment]
From my perspective, making a 1.{6..8}.1 wouldn't be difficult - @davidhassell given the utility of having the dates, would anything from your side speak against publishing those with the upcoming 1.9.0? I'd be willing to help.

**Comment by davidhassell** [comment]
Hi @erget, publishing `1.[78].1`  (1.6 already has its date) in Spetember alongside 1.9 is fine by me. 

If I understand the procedure correctly, we'd take a branch from the tagged commit, add the date and revision history to the branch and then tag that branch's commit as 1.x.1. Sounds good.

We'd then update https://cfconventions.org/documents.html to add the new versions.

**Comment by erget** [comment]
@davidhassell I lost the thread on this one - are you taking the lead here? Maybe this is something we can fix during CF Week next week.

**Comment by JonathanGregory** [comment]
CF1.9 states its release date, and so will later releases. In CF1.10 the revision history gives the release dates of all versions. These actions appear to address the concern, except that the CF1.7 and 1.8 documents do not state their own release dates within themselves. As discussed in this issue, that is hard to fix retrospectively. We would do it in an ideal world, but in this non-ideal world of finite working time, I suggest that we have other priorities and I propose to close this issue if no-one objects.

**Comment by davidhassell** [comment]
That sounds fine to me. Thanks, Jonathan.
