### ISSUE TITLE
Rework intro to Section 8: Accuracy & precision

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-conventions#330]
@JonathanGregory @AndersMS @davidhassell @oceandatalab (Sylvain) FYI

In pursuing #327 the following text was raised by @JonathanGregory (https://github.com/cf-convention/cf-conventions/issues/327#issuecomment-859397744), which we will not pursue in the course of #327 but should nonetheless be captured for referencing and addressing separately. I've quoted that below

In the first paragraph of Sect 8 we distinguish three methods of reduction of datset size. I would suggest minor clarifications:

> There are three methods for reducing dataset size: packing, lossless compression, and lossy compression. By packing we mean altering the data in a way that reduces its precision **(but has no other effect on accuracy)**. By lossless compression we mean techniques that store the data more efficiently and result in no **loss of precision or accuracy**. By lossy compression we mean techniques that store the data more efficiently **and retain its precision** but result in some loss in accuracy.

Then I think we could start a new paragraph with "Lossless compression only works in certain circumstances ...". By the way, isn't it the case that HDF supports per-variable gzipping? That wasn't available in the old netCDF data format for which this section was first written, so it's not mentioned, but perhaps it should be now.

**Comment by JonathanGregory** [comment]
Dear Daniel @erget 

I think it's fine to make this a separate issue, but in that case, will you leave that paragraph unchanged (as in version 1.8) in https://github.com/cf-convention/cf-conventions/issues/327?

Jonathan

**Comment by erget** [comment]
@JonathanGregory I'd pass this question on to @AndersMS who is doing the lion's share of work on this topic - currently I don't have the overview if you had other comments that would touch that paragraph, but we're addressing them in a systematic way there, so if there's something that's directly relevant for #327 that would be the place for it. WRT to the comment quoted above, as packing and compression, both lossy and lossless, are already part of the standard, I would see that as a separate improvement from those proposed in #327.

**Comment by AndersMS** [comment]
Hi @JonathanGregory and @erget 

We propose to change the firstagree with your proposed text. We have opened this issue (Rework intro to Section 8: Accuracy & precision · Issue #330 · cf-convention/cf-conventions (github.com)) to address per-variable gzipping as well as to verify that the usage if the terms precision and accuracy are correct.

**Comment by AndersMS** [comment]
Hi @JonathanGregory,

We propose to change the first paragraph as proposed by you in [#327](https://github.com/cf-convention/cf-conventions/issues/327#issuecomment-859397744). Additionally, we have opened this present issue #330  to address per-variable gzipping as well as to verify that the usage of the terms precision and accuracy are correct. 

Would you support that or would you prefer that we keep the paragraph as is for #327?

Anders

**Comment by JonathanGregory** [comment]
Dear @AndersMS and Daniel @erget 

I see. I misunderstood. If you think my version of the revised paragraph is OK, it's fine to include it in your pull request for https://github.com/cf-convention/cf-conventions/issues/327. I agree that my question about gzipping is a separate point, not related to https://github.com/cf-convention/cf-conventions/issues/327. If that's the subject of this issue, it makes sense to me.

Thanks, Jonathan

**Comment by JonathanGregory** [comment]
Fixed by https://github.com/cf-convention/cf-conventions/pull/326 of @AndersMS and @erget, thanks.
