### ISSUE TITLE
New standard name number_concentration_of_biological_taxon_pollen_grains_in_air

### ISSUE THREAD

**Issue by angilkaka** [cf-convention/cf-conventions#332]
Proposer's name AtMoDat Project - Angelika Heil
Date 2021-07-23
- Term:  number_concentration_of_biological_taxon_pollen_grains_in_air
- Description:   "Number concentration" means the number of particles or other specified objects per unit volume. "Pollen grain" refers to the male gametophyte of seed plants (either angiosperms or gymnosperms). The number concentration of pollen grains refers to the number of individual pollen grains per unit volume. "Biological taxon" is a name or other label identifying an organism or a group of organisms as belonging to a unit of classification in a hierarchical taxonomy. There must be an auxiliary coordinate variable with standard name biological_taxon_name to identify the taxon in human readable format and optionally an auxiliary coordinate variable with standard name biological_taxon_identifier to provide a machine-readable identifier. See Section 6.1.2 of the CF convention (version 1.8 or later) for information about biological taxon auxiliary coordinate variables.
- Units: m-3

Relevance: Numerical pollen forecasting is nowadays well established, but there are no CF standard names to write out model output in a standardised manner. 

Reference for definition of "Pollen grain": Galán et al. 2017: Recommended terminology for aerobiological studies, https://doi.org/10.1007/s10453-017-9496-0). 

The only new sentence in the term description is: "The number concentration of pollen grains refers to the number of individual pollen grains per unit volume. "Biological taxon" is a name or other label identifying an organism or a group of organisms as belonging to a unit of classification in a hierarchical taxonomy." The other sentences are taken from term descriptions of existing standard names. 

Hello, I would very much appreciate hearing your thoughts on whether this proposal is coherent. 
Thanks a lot!
Best regards
Angelika

**Comment by JonathanGregory** [comment]
I don't know about this subject, but the construction of your proposed standard name looks fine to me, thanks, @angilkaka

**Comment by roy-lowry** [comment]
It's a precedent - the first time we've had to deal with a part of an organism - but I think it's the best solution. The description extension looks excellent to me.

**Comment by angilkaka** [comment]
Dear Jonathan, dear  Roy, 

thanks a lot for your encouraging responses. 

There is a large potential user group for this standard name. Firstly, there is an increasing number of pollen modeling and measurement activities. Secondly, NetCDF as standard output file format is becoming more and more established in this context.  The introduction of CF standard names for pollen would enable users to store and share their output in a more FAIR manner. 

For Europe, for example, there are daily CAMS pollen forecasts
https://ads.atmosphere.copernicus.eu/cdsapp#!/dataset/cams-europe-air-quality-forecasts?tab=overview, publicly available in GRIB and NetCDF. 

There are also many activities on modeling atmospheric pollen concentrations elsewhere, e.g. using 
– GEM-MACH (Robichaud 2021: https:// doi.org/10.3390/atmos12060789),
– CMAQ-pollen (Efstathiou et al. 2011: https://doi.org/10.1016/j.atmosenv.2010.12.008),
– the "pollen-extended"  WRF-Chem (Werner et al. 2021: https://doi.org/10.1007/s00484-020-02045-1), 
– CHIMERE (Mesut et al. 2021:  https://doi.org/10.3390/atmos12060693),
– METRAS (Schueler and Schlünzen 2006:  https://doi.org/10.1007/s10666-006-9044-8).

I would therefore very much appreciate if you could support my proposal and add the proposed standard name to the CF table. 

Thank you and best regards
Angelika.




P.S.: For illustration, I drafted an example usage of the proposed pollen concentration standard name in a NetCDF file
dimension:
time = 6 ;
lat = 40 ;
lon = 60 ;
string80 = 80 ;
taxon = 11 ;
variables:
float time(time);
….
float pollen_conc(time,lat,lon,taxon) ;
pollen_conc:standard_name = "number_concentration_of_biological_taxon_pollen_grains_in_air“ ;
pollen_conc:units = „m-3“ ;
pollen_conc:coordinates = "taxon_lsid taxon_name“ ;
pollen_conc:long_name = „airborne pollen concentration“ ;
char taxon_name(taxon,string80) ;
taxon_name:standard_name = "biological_taxon_name“ ;
taxon_name:long_name = „pollen (Latin name)" ;
char taxon_lsid(taxon,string80) ;
taxon_lsid:standard_name = "biological_taxon_lsid“ ;
taxon_lsid:long_name = „ITIS identifier“ ;
taxon_lsid:url = „https://www.itis.gov/“ ;
char pollen_common_name(taxon,string80) ;
pollen_common_name:long_name = „pollen (common name)“ ;
pollen_common_name:description = „Common names as listed in ITIS“ ;
pollen_common_name:url = „https://www.itis.gov/“ ;
data:
time = 6., 12., ... ;
lat = 1., 2., ... ;
lon = 5., 6., ... ;
pollen_conc = 0.0087, 0.28367, ... ;
taxon_name = "Betula L.", "Poaceae", "Artemisia L.", "Ambrosia L.", "Secale L.", "Alnus Mill.", "Fraxinus L.", "Corylus L.", "Olea L.", "Fagus L.", "Quercus L." ;
taxon_lsid ="urn:lsid:itis.gov:itis_tsn:19478", "urn:lsid:itis.gov:itis_tsn:40351", "urn:lsid:itis.gov:itis_tsn:35431", "urn:lsid:itis.gov:itis_tsn:36495", "urn:lsid:itis.gov:itis_tsn:42089", "urn:lsid:itis.gov:itis_tsn:19466", "urn:lsid:itis.gov:itis_tsn:32928", "urn:lsid:itis.gov:itis_tsn:19505", "urn:lsid:itis.gov:itis_tsn:32989", "urn:lsid:itis.gov:itis_tsn:19461", "urn:lsid:itis.gov:itis_tsn:19276“ ;
pollen_common_name="birch", "grasses", "sagebrush", "ragweed", "rye", "alder", "ash", "hazelnut", "olive", "beech", "oak“ ;

**Comment by roy-lowry** [comment]
Dear Angilkaka. I think Fran will understand that Jonathan and I have both already supported your proposal though our positive comments.

**Comment by JonathanGregory** [comment]
It is possible that this proposal hasn't been noticed by the managers of standard names because this is an issue in the cf-conventions repository. Proposals for standard names should be made in the [`discuss` repository](https://github.com/cf-convention/discuss/issues). I suggest that you open a new issue in that repo, tagged standard name, and refer to this one from there. There's no need to repeat the above, but the thread could continue in that one instead. Sorry I didn't notice before. We should make sure that the templates clarify which repo should be used. Jonathan

**Comment by feggleton** [comment]
Apologies I didn't see this before. I will look at this properly shortly. Thanks

**Comment by feggleton** [comment]
@japamment Just flagging this to your attention in case I didn't mention it before.

**Comment by japamment** [comment]
The discussion here has moved to [#144](https://github.com/cf-convention/discuss/issues/144) in the discuss repository where the standard name has been accepted. Closing this issue now.
