### ISSUE TITLE
Fix syntax error in conformance doc

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-conventions#336]
When merging #326 a syntax error was introduced, which I have now corrected. @davidhassell would you mind cross-checking? Artefacts will be stored in the associated PR.

**Comment by davidhassell** [comment]
Thanks, @erget. I'm not sure what was introduced before, but adding the label looks good to me.

**Comment by erget** [comment]
Hi @davidhassell yes, I should have described better what I was trying to fix. Without a label it wasn't being recognised as a header - one saw the `===` as text rather than as a modifier of the chapter heading. I've checked the new build artefacts and with the label it looks as I would expect it to. Would you like me to merge it?

**Comment by davidhassell** [comment]
Got it, thanks. Please merge!
