### ISSUE TITLE
Clarification of newline usage

### ISSUE THREAD

**Issue by adigitoleo** [cf-convention/cf-conventions#347]
Hello, I'm currently implementing NetCDF capability for a Julia package, by using the excellent [NCDatasets.jl][1] package. The data comes from inversion models, and data from more than one model may be present in the file. I use an ancillary variable with `standard_name` of `source` to store the model name at each coordinate, following the [ancillary variables][2] guidelines. Next, I also want to use a global attribute called `source` to store the list of all model names.

From section [2.6.2][3]:

> For readability in ncdump outputs it is recommended to embed newline characters into long strings to break them into lines.

I use an operation like this:

```
"source" => join(unique(table.model), ",\n")
```

where `table.model` is the list of model names (strings). However, in the output of `ncdump -h` I see the raw newline codes:

```
		:source = "GSRM v2.1,\nITRF2014 [2016],\nNNR-MORVEL56,\nGEODVEL 2010,\nMORVEL 2010,\nITRF2008,\nAPKIM2005-DGFI,\nAPKIM2005-IGN,\nGSRM v1.2,\nCGPS 2004,\nREVEL 2000,\nITRF2000 (AS&B [2002]),\nHS3-NUVEL1A,\nAPKIM2000.0,\nITRF2000 (D&A [2001]),\nHS2-NUVEL1A,\nNUVEL 1A,\nNUVEL 1" ;
```

From another NetCDF file I had on my hardrive (CF 1.0), I get an output like this:

```
		:source = "CCSM3.0, version beta19 (2004): \n",
			"atmosphere: CAM3.0, T85L26;\n",
			"ocean     : POP1.4.3 (modified), gx1v3\n",
			"sea ice   : CSIM5.0, T85;\n",
			"land      : CLM3.0, gx1v3" ;
```

Any clarification on how this should be done? I'm using `netcdf library version 4.8.1 of Oct  1 2021 20:26:26`.

[3]: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#description-of-file-contents
[2]: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#ancillary-data
[1]: https://github.com/Alexander-Barth/NCDatasets.jl

**Comment by sethmcg** [comment]
It's noteworthy that ncdump renders an embedded newline as '\n' followed by an actual newline.  I'm not sure how this relates to the way that Julia works, but when I'm adding embedded newline characters to long strings in NCL, I just add a newline, not an escape sequence.  So I write code like this:

```
BR = str_get_nl()
parents = "Parent files had the following history attributes:"+BR
parents = parents + "Specific humidity file "+qfile+":"+BR
parents = parents + finq@history+BR
...
fout@history_of_parent_files = parents
```

and the string that I'm assigning to the netcdf attribute has embedded newline characters, not \n escapes. Then when I print it out with ncdump -h, it looks like this:

```     :history_of_parent_files = "Parent files had the following history attributes:\n",
                        "Specific humidity file huss.rcp85.GFDL-ESM2M.WRF.day.NAM-22i.mbcn-Daymet.nc:\n",
                        "Sat Sep 25 22:32:30 MDT 2021: huss.rcp85.GFDL-ESM2M.WRF.day.NAM-22i.raw.nc bias-corrected using MBCn with Daymet obs\n",
```

I've never worked with the netcdf library directly, so unfortunately I can't offer any advice on that front, but maybe this will at least help narrow down the nature of the problem.

**Comment by adigitoleo** [comment]
> It's noteworthy that ncdump renders an embedded newline as '\n' followed by an actual newline.

Thank you for the clarification.

>  when I'm adding embedded newline characters to long strings in NCL, I just add a newline, not an escape sequence

Interesting. I tried a few different ways of embedding the newline in Julia but they haven't worked so far. It looks like NCAR uses [CRLF for newlines][1], but even Julia's `'\r\n'` doesn't seem to work. I can use raw strings:

```
s = """foo
bar"""
```

but Julia always puts `'\n'` at the line endings. I was as yet unable to find the actual definition of that `BR` symbol in the NCAR sources, if anyone could point me to where the string ops are defined I could take a look, although I'll be going in blind with C/fortran.

Alternatively I could check the ncdump sources for the line splitting logic...

[1]: https://github.com/likev/ncl/blob/49a124bbfc0247a6a8768e9c5084c18fc2207d1e/ncl_ncarg_src/ni/src/ncl/editline.c#L72

**Comment by adigitoleo** [comment]
I should clarify: when I use `'\r\n'`, I see only the first line. So the newline is perhaps being embedded, but there is no `'\n'` at the end and the other lines disappear.

**Comment by sethmcg** [comment]
BR is just a variable, defined on the first line as the output of `str_get_nl()`

**Comment by adigitoleo** [comment]
Thanks, I guess I need to find out what `str_get_nl` is doing.

Comment about `\r\n` was inaccurate, I was using the wrong dataset. It doesn't work in the same way as `\n`, i.e. the symbols appear in the output but the line is not split.

**Comment by Dave-Allured** [comment]
@adigitoleo, you are simply seeing an inconsistency in **ncdump**.   Recent version of this utility are not consistent for displaying embedded newlines in attributes.  This varies with the type of the internal file format.  Notice that true newline characters are displayed with the escape sequence "**\n**" inside quotes, in all cases.  However, **netcdf-3** and **netcdf4-classic** formats also add the extra visual line break.  From **ncdump -hs**:

    :A = "line 1\n",
        "line 2" ;
    :_Format = "netCDF-4 classic model" ;

Whereas **full netcdf-4** format does not include the extra visual break:

    :A = "line 1\nline 2" ;
    :_Format = "netCDF-4" ;

The first style is traditional and was ubiquitous for several years, until support for string data type evolved in one of the early netcdf-4 library versions.   I believe that the CF readability policy was conceived early, and was based only on the traditional netcdf-3 behavior.

**Comment by adigitoleo** [comment]
@Dave-Allured I see, thanks. I'll stop worrying about it in that case. Perhaps this could be mentioned in the spec somewhere as a caveat or something. Otherwise this can probably be closed.

**Comment by Dave-Allured** [comment]
I agree with the original rationale of CF section 2.6.2, embed newline characters into long strings to break them into lines, for readability whenever possible.

Now there is a complication.  **Full netcdf-4** format offers two different string data types; **character** and **string**.  I think with introduction of the formal **string** data type, **ncdump** was changed for **both** data types, so that visual line breaks would be used **only to separate elements of an array of strings**.  I think the new intent was that if you want to display multiple lines, you are supposed to use an **array of strings**, rather than newline delimiters.

The traditional **character** data type supports only a 1-dimensional array of single characters.  Therefore the **original** intent of **ncdump** was to provide use of newlines to embed visual line breaks.

The result was a developer's choice to switch the display style based on the file format type.  At this time there is not much to be done to change that.

This dichotomy creates some challenges for standards, and for conversions between the two data types.  Note that writing formal **string** data type with embedded newlines is still perfectly legal according to basic netcdf-4 rules.  I have not looked up how CF handles this.

I advise not making any reading code that depends specifically on one or the other of these two newline strategies.  It would be reasonable to have code that knows how to digest both strategies in a smart way, so that the application does the right thing and gets an equivalent result for both cases.

**Comment by larsbarring** [comment]
Yes, I agree with @Dave-Allured, especially as [section 2.6.2](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#description-of-file-contents) only is a *recommendation* that some may follow and others may not, and the word "readability" may be interpreted differently.

**Comment by zklaus** [comment]
I think we should see `ncdump` as what it is, that is essentially a 3rd party debug tool. As such, its specific choice of output format, regrettable as it may be, doesn't have bearing on the CF conventions and imho poses no challenge to standards.

**Comment by adigitoleo** [comment]
OK I think this can be closed, I agree that if anything this is a ncdump issue. Thanks.
