### ISSUE TITLE
Delete unnecessary `Conventions` attribute in two examples

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-conventions#349]
Linked [pull request](https://github.com/cf-convention/cf-conventions/pull/350)

Dear all

I propose the deletion of the `Conventions` attribute from Examples 7.15 and 7.16 in Section 7.5 on Geometries. Although it may seem odd to delete information, I think the attribute here isn't really informative. Including it is a defect, and removing it is a correction. My reasons for thinking this are:

* These are the only examples in the whole document that contain the `Conventions` attribute (as has been discussed [elsewhere](https://github.com/cf-convention/cf-conventions/issues/343)), so it's inconsistent. We couldn't make the document consistent by including `Conventions` in all other examples, because most of them are just fragments of CDL. They don't show global attributes, which would be irrelevant and hence distracting to the point being illustrated.

* Keeping `Conventions` only in these two examples might imply it was particularly significant, more than in all other examples which don't include it. This isn't so. I guess that it might have been included to make the point, at the time the proposal was drafted, that the feature didn't exist in the version that was the present release at that time. Maybe @dblodgett can remember?

Best wishes

Jonathan

**Comment by erget** [comment]
@JonathanGregory I support this proposal, examples are most illustrative when they contain the minimal material to demonstrate what they're about. In that context the `Conventions` attribute is a distraction requiring additional maintenance.

**Comment by taylor13** [comment]
I support this proposal too (for the same reasons).

**Comment by davidhassell** [comment]
I support this as well.

**Comment by JonathanGregory** [comment]
Thank you all for supporting this. I have created a [pull request](https://github.com/cf-convention/cf-conventions/pull/350), which can be merged in three weeks from now (since this is a defect issue) on 1st February, if no-one objects before then. Jonathan

**Comment by JonathanGregory** [comment]
This is a defect and no-one has objected, so the [pull request](https://github.com/cf-convention/cf-conventions/pull/350) could be merged today. Please could someone oblige? Thanks.
