### ISSUE TITLE
Are geometries allowed to self-intersect?

### ISSUE THREAD

**Issue by benjwadams** [cf-convention/cf-conventions#354]
In CF Conventions section 7.5 a number of cases for geometries are supplied.   Are "line" and "polygon" geometries as well as individual multipart analogs allowed to self-intersect themselves?

**Comment by dblodgett-usgs** [comment]
From my recollection, there are no rules on topology in the spec, so yes. Self intersections are fine.

**Comment by davidhassell** [comment]
Hello,

I agree with Dave that there are no rules on that, but I'd like to fully understand what you are suggesting for polygons. Do you mean "are different  _parts_ of a multi-part polygon allowed to overlap" or do you mean "are different _edges_ of an individual polygon part allowed to intersect"? The latter case could look like this polygon part with 5 nodes: 
![star_polygon2](https://user-images.githubusercontent.com/8126576/153163392-f77c5224-c87b-456c-9553-c3c1974d4025.png)
Thanks, David

**Comment by chris-little** [comment]
I think that the main implication of allowing self intersecting edges of a polygon (like the possibly 5, probably 2 1/2 sided polygon from @davidhassell above) is people may use the wrong inside/outside algorithms and get unexpected results.
The main ones are left-hand/right-hand, winding number, and counting crossings from infinity. [SVG explains this well](https://www.w3.org/TR/2008/REC-SVGTiny12-20081222/painting.html#FillProperties).

As people often choose the wrong algorithm anyway, I think allowing self-intersecting edges is OK, as it is the most general case, and "less is more". Whether implementations cope with multi-part, self-intersecting polygons is another issue.

**Comment by zklaus** [comment]
There certainly are ways to interpret self-intersecting polygons in a consistent manner. But is there a use-case for this in the realm of CF? For self-intersecting lines, this seems clear (any kind of route, for instance, from ships, planes, etc.), but for polygons, I struggle. Hence my intuition would be to at least discourage their use.

For a better understanding, I would rather look to other geo packages and standards than to inspiration from the world of graphic design. Starting points might be [Shapely](https://shapely.readthedocs.io), [GEOS](https://libgeos.org/), or the OGC's [Simple Feature Access](https://www.ogc.org/standards/sfa).

**Comment by dblodgett-usgs** [comment]
We have lots and lots of polygons with self intersections where the polygon closes on itself at a node. It may not cross but it does need to pinch off an open back up -- so an intersection is real. 

I don't think CF should have a horse in this race.

![image](https://user-images.githubusercontent.com/1492803/153221223-94c64e16-3746-4580-9f4b-a2b97f9003a1.png)

**Comment by roy-lowry** [comment]
My experience of spatial databases (Oracle Spatial about 5 years ago) is that self-intersections caused the geometry to be tagged as invalid forcing it to be constructed from a collection of simple polygons. Geometries need to work with established tools which will dictate any standards.

**Comment by Dave-Allured** [comment]
The role of CF is rules for metadata, which is mainly labeling and data structures.  CF should try to stay within that role and avoid content details, notwithstanding the current complexity of section 7.5.  Geometry consistency and compatibility is well addressed by other conventions.  CF should either remain silent on the consistency of geometry, or else simply state that it is not regulated.

**Comment by zklaus** [comment]
I think it's good when CF files can be interpreted, ideally both by humans and computers, and ideally unambiguously. That means it should be easy, for example, to color in in the five pointed star posted by @davidhassell above, which region should be used for averaging over this geometry. It seems that @Dave-Allured's position amounts to saying this should not only not be easy, it should not be well-defined because that would be overstepping CF's mandate.

Most likely, I misunderstand, but I certainly think that would be an unfortunate interpretation of CF's role.
