### ISSUE TITLE
Update PR template to ask proposers to update History and Contributors themselves

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-conventions#359]
At the CF Community Meeting 2020 we proposed asking contributors to add themselves to the authors list if they are contributing substantially enough to the Conventions that their names should be included there.

I think this would be a good idea to include in `CONTRIBUTING.md` but we also need some guidelines on who should "count" as an author.

@davidhassell do you have any thoughts here? Anybody else interested in chipping in?

**Comment by taylor13** [comment]
I can't come up with anything completely objective.  Perhaps folks who think they're deserving should nominate themselves (or others could nominate), and if the CF committee chair or anyone on the governance board supports the nomination, the person would be included.  It would be nice to provide some guidance though on what we consider "deserving"

We might also consider a "contributing author" category for anyone participating in multiple substantive issue discussions.

**Comment by JonathanGregory** [comment]
Dear all

For standard names, we have a [list of contributors](http://cfconventions.org/Data/cf-standard-names/docs/standard-name-contributors.html), with a preamble which says, _The following individuals have proposed standard names or participated substantially in discussions which have led to the definition of standard names. They are listed here in recognition of their contribution to the development of the CF standard._ As secretary of standard names, Alison @japamment adds to this list whenever she implements changes to the standard name table.

Those who proposed changes made in the conventions are recognised by being named as contributing authors of the conventions document. I agree it would be good and fair to recognise other contributors to discussions on new conventions. I suggest that we give the secretary of the conventions and the chair of the committee (currently @davidhassell and me) the joint responsibility of compiling a web page containing a list of contributors to conventions discussions, to be updated at least annually, by including everyone who has made a non-trivial contribution to any successfully concluded conventions issue.

Jonathan

**Comment by erget** [comment]
Hi @JonathanGregory , this is a good idea - I think this would be a good way of giving credit for the valuable contributions from within the community.

**Comment by JonathanGregory** [comment]
No-one disagreed with the suggestion here. If we use a web page for the purpose, it will not be a change to the convention document. Hence I will close this issue and open one in the web/governance repo.
