### ISSUE TITLE
Provide additional guidance on moderating issues

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-conventions#362]
Spawned from this item in #275:

> Jonathan: To record David’s suggestion of making a comment in the issue when the summary is updated, in order that everyone will be notified, and also because the moderator’s summary is part of the discussion and needs to be recorded therein for the discussion to make sense when read subsequently

Concretely I interpret this to mean that CONTRIBUTING.md should be updated to:
1. Specify that the moderator should summarise the discussion in an issue by updating the issue's description occasionally, and make a comment in the issue doing so. This ensures that everyone is notified, and records the moderator’s summary as part of the discussion for future reference
2. At the end of discussion, announce the merge date - and then merge on that date.

Additionally, if we adopt Kanban, this could signify a transition to a "ready for merge" column or something similar.

@JonathanGregory I take it this is in line with what you were thinking as well?

**Comment by JonathanGregory** [comment]
Thanks, Daniel @erget. That's fine. Sorry for my stupidly long title, caused by my submitting the comment prematurely.

**Comment by erget** [comment]
No worries @JonathanGregory :) I'll try to have the PR ready sometime next week.
