### ISSUE TITLE
Rename GitHubProblem label

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-conventions#363]
I suggest that we change the `GitHubProblem` label to `GitHubUsage`, which is how we describe this kind of issue. It's not necessarily a problem with GitHub. (Note: this is a self-referential issue - I hope that won't cause GitHub to get caught up in an infinite loop.)

**Comment by erget** [comment]
I support this idea, I've scratched my head about that label previously but hadn't followed it back to where it lived.

**Comment by davidhassell** [comment]
I support this, too.

**Comment by zklaus** [comment]
As long as we are renaming, we might consider adding spaces, so I would suggest `Github Usage` or `github usage`.

**Comment by sadielbartholomew** [comment]
Not sure if any further agreement is required or wanted, but I also support this as the new label will be much clearer for the reason Jonathan outlines.

**Comment by erget** [comment]
Just made a PR that fixes this - anyone willing to review? If it's ok we can merge straightaway.
