### ISSUE TITLE
Extraneous space after asciidoc formatting

### ISSUE THREAD

**Issue by dnowacki-usgs** [cf-convention/cf-conventions#381]
In reading through the CF Conventions document, I noticed what seem to be extraneous spaces between AsciiDoc formatting and punctuation marks. For instance, consider [this text in section 1.4](https://github.com/cf-convention/cf-conventions/blob/main/ch01.adoc):

```
Each variable in a netCDF file has an associated description which is provided by the attributes **`units`** , **`long_name`** , and **`standard_name`** . The **`units`** , and **`long_name`** attributes are defined in the NUG and the **`standard_name`** attribute is defined in this document.
```

I've reproduced the first instance below:

``**`units`** ,``

Note the space between the bolded, monospaced units text and the comma that follows.

I have found examples between formatted text and following commas, periods, and parentheses. Spaces also sometimes occur after cross-references (using ``<<>>`` syntax). In one or two cases I have found an example with a space between a preceding parenthesis and formatted text. 

Given the spaces generally don't exist for non-formatted text (e.g., there is no space between the word "document" and the  period in the example sentence above), it doesn't seem to be a conscious style decision. It's also not a limitation of AsciiDoc as far as I can tell; after removing some example spaces I built the text locally successfully with asciidoctor.

Would folks be supportive of a PR removing these spaces? Or am I misunderstanding an intentional decision?

**Comment by erget** [comment]
Hi @dnowacki-usgs , thanks for these ideas - actually we are [planning a few hackathons](https://github.com/cf-convention/discuss/issues/152) at the [upcoming CF Community Meeting](https://cfconventions.org/Meetings/2022-Workshop.html) and this sounds like it would be well-aligned with cleanup work plus creating / endorsing use of an AsciiDoc style guide. Are you coming to the workshop? Your participation would be very welcome, hybrid or in-person! Otherwise a PR would be useful, as we could use that as a starting point for a syntax cleanup.

**Comment by dnowacki-usgs** [comment]
Okay, I have started a pull request that removes extraneous spaces. This addresses spaces preceding `.,])` and spaces following `[(`. I didn't modify anything in the ncdump-ish output code blocks or most other code blocks, although there were a few that I changed—mostly in pseudo code function definitions.

As for a style guide, I didn't see much out there. I was unable to find any black-style automated doc formatters for AsciiDoc. This [recommended practices](https://asciidoctor.org/docs/asciidoc-recommended-practices/) document is among the few I could find for a starting point for a style guide.

**Comment by erget** [comment]
I like the recommended practices - thanks for the PR! This puts us on good footing for the upcoming hackathons :)

**Comment by erget** [comment]
Hi @dnowacki-usgs - we're startng our hackathons in a few hours from https://github.com/cf-convention/cf-conventions/tree/386-cleanup-line-breaks-asciidoc - still WIP but you might be interested. Is https://github.com/cf-convention/cf-conventions/pull/382 ready to be merged?

**Comment by erget** [comment]
The commits in #382 have been merged as part of the merge of https://github.com/cf-convention/cf-conventions/issues/386. Thanks a bunch @dnowacki-usgs !
