### ISSUE TITLE
Automated build of documents not working with single-sourced version

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/cf-conventions#388]
Whilst building the documents for the public release of CF-1.10, I encountered some failures with the automated GitHub actions. These action were triggered by the creation of a new "Release".  The details can be found at https://github.com/cf-convention/cf-conventions/actions/runs/2962652688

As a workaround, I ran the asciidoc commands (taken verbatim from in https://github.com/cf-convention/cf-conventions/blob/main/.github/workflows/adoc_build.yml) on the command line and successfully built the documents

The build of the PDF of the conformance document wouldn't work on the command line either, but this artefact is no currently posted to the web site, so that was not a problem for CF-1.10. However, we _should_ provide a PDF of the conformance document for future versions.

Many thanks for @zklaus for putting all this worthy improvement together in the first place! (https://github.com/cf-convention/cf-conventions/issues/343)

**Comment by zklaus** [comment]
Since testing this requires making releases, I'll try to do a few releases without uploading any artifacts in my fork and report back here with results. Thanks for pointing out the problems, @davidhassell!

**Comment by davidhassell** [comment]
Hi @zklaus  - this issue - https://github.com/cf-convention/cf-conventions/issues/391 - might also be as asciidoc problem ... I'm not sure, though

**Comment by zklaus** [comment]
I think the original problem here was one of escaping, i.e. too many quotation marks in the workflow file. This is addressed in PR #396.
