### ISSUE TITLE
Fix figure caption issues from updating line breaks

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-conventions#389]
Cleanup complete - except that it looks like the figure captions may be broken in
- `appi.adoc`
- `appj.adoc`
- `ch07.adoc`
- `ch08.adoc`

_Originally posted by @erget in https://github.com/cf-convention/cf-conventions/issues/387#issuecomment-1245348672_

**Comment by sadielbartholomew** [comment]
Just tweaking the name of the Issue here so it can easily be differentiated from another one I am about to open which regards follow-on from the initial cleanup in #387.

**Comment by erget** [comment]
Problems sighted on pages in PDF, numbers are absolute page numbers, not the footer numbering
- [ ] 73
- [ ] 110
- [ ] 201
- [ ] 204
- [ ] 206
- [ ] 220

Found by searching for "image::images"

**Comment by erget** [comment]
Ready for review

**Comment by sadielbartholomew** [comment]
Happy to review the PR today if you'd like Daniel?

**Comment by erget** [comment]
Yes please!
