### ISSUE TITLE
Broken references tags in the latest release (1.10) Convention pdf 

### ISSUE THREAD

**Issue by jypeter** [cf-convention/cf-conventions#395]
I have just noticed that, in the _Convention_ documents available from the [website homepage](http://cfconventions.org/)
- the tags in the web version of the references are OK in the [HTML version](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#_bibliography). e.g. _[IEEE_754] [IEEE Standard for Floating-Point Arithmetic](https://ieeexplore.ieee.org/servlet/opac?punumber=8766227)_
- are missing from the [pdf version of 1.10](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.pdf)! e.g. _[] IEEE Standard for Floating-Point Arithmetic_
- are OK in the [pdf version of the working draft
](http://cfconventions.org/cf-conventions/cf-conventions.pdf)

**Comment by larsbarring** [comment]
#391 (and [#250](https://github.com/cf-convention/cf-convention.github.io/issues/250#issue-1363547612))

**Comment by jypeter** [comment]
OK, this seems to be a duplicate (soon to be fixed?)!
