### ISSUE TITLE
Minor style fixes in Conventions doc

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-conventions#400]
Whilst doing #397 I did an unsystematic review of the document and noted the following things which are a bit annoying now that we have a style guide. Might want to fix these and search for further instances that are worth hunting.

- [x] Not everything that I think should be monotyped is.
  - [x] §5.6.1 - some attributes are normal type (`grid_mapping_name`, `grid_mapping_variable` (should be italicised), `grid_mapping`, `<coordinatesVariable>`, `standard_name`, `latitude_longitude`, `crs_wkt`, `crs`), some are superfluously bolded
  - [x] H.3 - caption of example could use some monotyping. Probably also in other captions.
- [x] Naked URLS, e.g. in §6
- [x] Bolded, not monotype in Table F.1: "fixed_angle_axis", "sweep_angle_axis"
- [x] Consistent line spacing?

**Comment by JonathanGregory** [comment]
Dear Daniel @erget 

What's the status of your PR #401 to correct some minor style errors? I see there was quite a lot of discussion in the PR. Is it still a work in progress?

Thanks

Jonathan

**Comment by JonathanGregory** [comment]
Dear Daniel @erget 

What's the status of your PR https://github.com/cf-convention/cf-conventions/pull/401 to correct some minor style errors? Will you have time to respond to the comments and update it? Thanks for doing it.

Best wishes

Jonathan

**Comment by erget** [comment]
A lot of good work went into this! I'm embarrassed it fell between the cracks on my side. Yes, I will have a look once back in office, will target having it done in next 2w or so

**Comment by JonathanGregory** [comment]
Thanks, Daniel

**Comment by JonathanGregory** [comment]
And thanks again, Daniel @erget and @sadielbartholomew.
