### ISSUE TITLE
Remove duplicated section 8.2 in conformance document

### ISSUE THREAD

**Issue by RosalynHatcher** [cf-convention/cf-conventions#406]
# Title
Remove duplicated section 8.2 in Conformance Document
# Moderator
@user
# Requirement Summary
When Section 8.2 was renamed from "Compression by Gathering" to "Lossless Compression by Gathering" at CF-1.9 the section got duplicated in the conformance document rather than renamed.
# Technical Proposal Summary
Remove section entitled "8.2 Compression by Gathering".
# Benefits
Conformance document is updated in line with the Conventions document.
# Associated pull request
#407

**Comment by JonathanGregory** [comment]
Thanks for opening this issue, Ros @RosalynHatcher, and preparing the pull request to correct it. Much longer than three weeks have passed, so I have merged it.
