### ISSUE TITLE
Missing 'and' in CONTRIBUTING.md instruction

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/cf-conventions#416]
# Missing 'and' in CONTRIBUTING.md instruction

# Moderator
@taylor13 (who originally spotted this defect)
# Requirement Summary
Add missing `and` in one of the CONTRIBUTING.md instructions
# Benefits
Contributing instructions become clearer.
# Technical Proposal Summary
Add missing `and` in one of the CONTRIBUTING.md instructions
# Benefits
Contributors
# Status Quo
Contributing instructions are unclear
# Associated pull request
#415
# Detailed Proposal
Change "Practically all changes should be documented and discussed in an issue fixed in a related pull request." to "Practically all changes should be documented and discussed in an issue **and** fixed in a related pull request."

**Comment by larsbarring** [comment]
@davidhassell: ... make a PR and merge it? :-)

**Comment by larsbarring** [comment]
I am tying together some loose ends here: the corresponding PR seems to exist as #415.

**Comment by larsbarring** [comment]
....and then I saw that the lik already existed ....

**Comment by larsbarring** [comment]
closed via #415
