### ISSUE TITLE
Add missing examples to LoE (list of examples)

### ISSUE THREAD

**Issue by neumannd** [cf-convention/cf-conventions#418]
# Title
Add missing examples to LoE (list of examples)

# Moderator
@user

# Requirement Summary
The list of examples (LoE) should contain all examples. Currently, it does not contain all examples.

# Technical Proposal Summary
Add links to all examples to the LoE in `toc-extra.adoc`

# Benefits
Examples can be found via the LoE

# Status Quo
Several examples are missing in the LoE

# Associated pull request
#450

# Detailed Proposal
Several examples are missing in the LoE. The linked PR contains changes in the `toc-extra.adoc` which solve this (examples are added to LoE). Additionally, minor changes are implemented:

* Example I.1 now has the caption "Example I.1"
* caption "Examples 1.1. " was changes to "Example 2.1. " (because it is in chapter/section 2 and not in chapter/section 1)
* changed "5.13." to "5.14." because a new examples 5.13 was inserted
* appended a space to caption `"Table D.1."` => `"Table D.1. "`
* added captions `Table I.1. ` and `Table I.1. `
* added a  `.` to a caption in chapter 3

# Note

Exmplae 8.7 was added to the LoE in this Issue (and PR !) but also in Issue #286 (PR #417). All other changes are only part of one of both issues/PRs.

**Comment by neumannd** [comment]
Update to this issue: I had forgotten to add the related PR to the issue descrition. This was updated.

**Comment by neumannd** [comment]
Might be decided in combination with #286 and #420

**Comment by JonathanGregory** [comment]
Since this is a defect issue and no-one has objected to the corrections, I will merge the linked [PR 419](https://github.com/cf-convention/cf-conventions/pull/419) at the same time as [PR 417](https://github.com/cf-convention/cf-conventions/pull/417), which addresses [issue 286](https://github.com/cf-convention/cf-conventions/issues/286). As discussed in that issue, the two pull requests affect some of the same areas and both are needed. Thanks, @neumannd.

**Comment by JonathanGregory** [comment]
#419 now has conflicts to be resolved, because of #417 being merged. Please could you resolve them, @neumannd?

**Comment by JonathanGregory** [comment]
OK, fine. At the same time, perhaps you could modify the entries in `history.adoc` to mention that you've also corrected the titles of three tables, as well as the four examples. Many thanks.

**Comment by neumannd** [comment]
@JonathanGregory I'll set a a new PR. Rebasing the old one causes many conflicts ... .

**Comment by neumannd** [comment]
@JonathanGregory new PR is #450

**Comment by JonathanGregory** [comment]
Very good - thanks. I'll merge it now.

**Comment by neumannd** [comment]
Thanks for taking time and merging it 👍
