### ISSUE TITLE
Add List of Figures

### ISSUE THREAD

**Issue by neumannd** [cf-convention/cf-conventions#420]
# Title
Add List of Figures

# Moderator
@davidhassell 

# Moderator Status Review [last updated: YYYY-MM-DD]
Brief comment on current status, update periodically

# Requirement Summary
It would be useful to have a "List of Figures" because there is a "List of Examples" and a "List of Tables".

# Technical Proposal Summary
Add a "List of Figures" to `toc-extra.adoc`

# Benefits
Readers can easily find the figures

# Status Quo
There is a "List of Examples" and a "List of Tables" but no "List of Figures"

# Associated pull request
PR #451

# Detailed Proposal
Add a "List of Figures" to `toc-extra.adoc`

**Comment by JonathanGregory** [comment]
Thank you for doing this, @neumannd. I think this will be a useful addition.

**Comment by neumannd** [comment]
Would anyone volunteer to be moderator of this?

**Comment by davidhassell** [comment]
I'd be glad to moderate.

**Comment by neumannd** [comment]
@davidhassell Thanks. I added you to the description of the proposal.

**Comment by neumannd** [comment]
Any objections?

**Comment by neumannd** [comment]
Might be decided in combination with #286 and #418

**Comment by neumannd** [comment]
@JonathanGregory @davidhassell New PR based on current main branch.

**Comment by JonathanGregory** [comment]
Thanks, @neumannd. The list of figures will be useful. The PR also contains the changes we merged yesterday, though - they shouldn't be there, should they?

**Comment by JonathanGregory** [comment]
Thanks again, @neumannd. That looks good to me. This is a useful enhancement. @davidhassell, as moderator, do you think it's OK?

**Comment by neumannd** [comment]
@davidhassell reminder

**Comment by JonathanGregory** [comment]
I will merge this now. No-one objected to the idea and sufficient support was expressed, and more than enough time has passed. Thanks, @neumannd.
