### ISSUE TITLE
Make Packed Data section (CF 8.1) integer types consistent with Data Types section (CF 2.2)

### ISSUE THREAD

**Issue by cofinoa** [cf-convention/cf-conventions#427]
Before submitting an issue be sure you have read and understand the github contributing guidelines: https://github.com/cf-convention/cf-conventions/blob/main/CONTRIBUTING.md and the rules for CF changes: http://cfconventions.org/rules.html

Change proposals should include the following information as applicable.
If important to the issue, the problem text should be pasted in the body of the issue and proposed fix included.
A link to the line where the problem exists could also be included.
Alternatively, a pull request can be used to describe the problem and the proposed solution more precisely.

# Title
Make CF 8.1 (Packed Data) integer types consistent with Data Types (CF 2.2)
# Moderator
@user
# Requirement Summary
Make consistent packed data section
# Technical Proposal Summary
Make Data Packed section with *any-integer*   in Data Types section
# Benefits
Use of the *new* netCDF4 integer types as storage for packed data (CF-1.9)
# Status Quo
See cf-convention/discuss#202
# Associated pull request
#425 
# Detailed Proposal
The Data Packed section (CF 8.1) enumerates integer data types: 
>  ... the variable containing the packed data must be of type `byte`, `short` or `int`.

but it misses new integer data types introduced in CF-1.9 (#243 #244  #294). 

The proposed change is to remove the explicit enumeration on integer types and add a reference to the Data Types section (CF 2.2):
> ... the variable containing the packed data must be of an integer type (see `<<data-types>>`).

**Comment by JonathanGregory** [comment]
Dear Antonio @cofinoa 

Thanks for opening this. Is it related to [issue 374](https://github.com/cf-convention/cf-conventions/issues/374), raised by Ken Mankoff?

Best wishes

Jonathan

**Comment by cofinoa** [comment]
Dear Jonathan (@JonathanGregory),

The reason for this issue was cf-convention/discuss#202. I wasn't aware about issue #374 but after reading it, this issue is also related to it. 

The issue #374 is missing all `unsigned` integers introduce on CF-1.9 that can be also used for data packing. 

My proposal would be remove the explicit enumeration of integer types, and make reference to *any integer type* or *an integer type* as it is been mentioned on Data Types section (CF 2.2), to fix (IMO) the missing unsigned integer types on Data Pack section (CF 8.1). 

With respect to issue #374, I would just keep separated from this and wait for a decision been made with respect to it, and modify (or not) Data Pack section (CF 8.1).

**Comment by JonathanGregory** [comment]
Dear Antonio @cofinoa 

Thanks for looking at it. In that case, we have more urgency to to decide about [374](https://github.com/cf-convention/cf-conventions/issues/374). As you will see from my contribution to that issue, I'm not clear what is intended by the existing text giving restrictions on packing. No-one else has offered an interpretation. It would be very helpful if you or anyone else who uses packing could contribute thoughts to 374.

Best wishes and thanks

Jonathan

**Comment by JonathanGregory** [comment]
Dear @cofinoa and others

I have proposed text in [374](https://github.com/cf-convention/cf-conventions/issues/374) to resolve this issue as well as that one. Please have a look.

Thanks and best wishes

Jonathan

**Comment by JonathanGregory** [comment]
I'm closing this issue because I believe it's being addressed in #374.  If you disagree, please either reopen this issue, or comment in #374.
