### ISSUE TITLE
Typo in end-date in example 7.12

### ISSUE THREAD

**Issue by heikoklein** [cf-convention/cf-conventions#449]
Example 7.12 describes the winter-season 2007-2008, but the climatological end-bound was given in August 2000. This is fixed to March 2008 in the PR.

# Associated pull request
Link to associated pull request, if present.
https://github.com/cf-convention/cf-conventions/pull/448

**Comment by JonathanGregory** [comment]
Dear Heiko

Thank you for reporting this and preparing a correction. I agree with the modification to the text of the example. Please could you add this issue to `history.adoc`.

This issue corrects a defect, and as such it will be accepted in three weeks (on 15th September) if no-one objects to it.

Best wishes

Jonathan

**Comment by heikoklein** [comment]
Dear Jonathan,
the pull-request #448 has been updated to include this issue in `history.adoc`.
Best wishes,
Heiko

**Comment by JonathanGregory** [comment]
Thanks again, Heiko.

**Comment by JonathanGregory** [comment]
Three weeks have passed with no objection to this defect correction, so I will merge the pull request now. Thanks, @heikoklein.

**Comment by JonathanGregory** [comment]
Before merging, I resolved a conflict at the top of `history.adoc` by reordering the most recent entries.
