### ISSUE TITLE
CF variable names can be impossible to parse in ancillary variables

### ISSUE THREAD

**Issue by benjwadams** [cf-convention/cf-conventions#453]
[Section 2.5](https://cfconventions.org/cf-conventions/cf-conventions.html#variables) reads:
> 2.5. Variables
>This convention does not standardize variable names.

Variable names can include numerous characters, the most pertinent here are space and blank characters.  NetCDF accepts spaces in variable names and even will allow trailing spaces if they are higher Unicode code points that are considered spaces:

https://github.com/Unidata/netcdf-c/blob/main/libdispatch/dstring.c#L167-L220

The following code creates *valid* NetCDF variables with valid names:

```
from netCDF4 import Dataset

ds = Dataset("nonesuch.nc", "w", diskless=True)
# spaces in variable names
ds.createVariable("A mi me encanta los espacios", "i4")
# you can even tack them on the end if they're certain unicode characters!
ds.createVariable("totally valid" + "\u2006"*10, "i4")
```

All of this is within spec, however [section 3.4](https://cfconventions.org/cf-conventions/cf-conventions.html#ancillary-data) says (emphasis mine):

> The attribute `ancillary_variables`  ... is a string attribute whose value is a blank separated list of variable names.

For one thing, "blank" is rather vague and could encompass quite a few Unicode blank and spacing characters.  Is this intentional?

On the other hand, depending on what a blank is, certain variable names are going to be impossible to parse in the `ancillary_variables` attribute.  Take for example, "water temperature",   `ancillary_variables for something associated with water temperature will be "water temperature" and according to spec, this should be "blank separated", so software checking CF is likely to split into "water" and "temperature", which likely won't exist, and weren't the intended variable references anyhow.

The most reasonable possible fixes going forward are to either limit the variable names in CF to where they cannot contain whitespace characters or to implement some sort of quoting using some sort of characters not allowed as identifiers by NetCDF. 

E.g.

`ancillary_variables = "'water temperature' 'water conductivity'"`

**Comment by larsbarring** [comment]
If you look at the preceding [section 2.3](https://cfconventions.org/cf-conventions/cf-conventions.html#_naming_conventions) you will find
>Variable, dimension, attribute and group names should begin with a letter and be composed of letters, digits, and underscores. Note that this is in conformance with the COARDS conventions, but is more restrictive than the netCDF interface which allows use of the hyphen character. 

This piece of text was written some 20 years ago when the ASCII character set dominated. But with the introduction of Unicode this is now ambiguous, especially -- as you point out -- with recent developments of netCDF. 

There is an ongoing discussion about this in #237.

**Comment by benjwadams** [comment]
I had forgotten about the limitation of CF variable names despite maintaining a checker.   Closing in favor of continuing discussion in #237.
