### ISSUE TITLE
Update NUG link to Data Types in ch02.adoc

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/cf-conventions#458]
@bzah found a broken link to NUG in chapter `2.2 Data Types` and located the correct link. With the recent enhancement of the text related to packing/unpacking (#374 and #456) this link even more relevant. Thanks Abel for spotting this!

Would you @bzah mind also updating the history (cf. [history.adoc](https://github.com/cf-convention/cf-conventions/blob/main/history.adoc) in the PR)

 
# Associated pull request
#444

As the PR was created already on August 9, I believe it can be merged as soon as ready, i.e. without the cool down period.

**Comment by bzah** [comment]
Hi, thanks Lars for opening the issue. 
I don't have anything else to add to the PR, can we merge this now ?

**Comment by JonathanGregory** [comment]
Thanks for opening the issue, @larsbarring, and thanks for finding and fixing the problem, Abel @bzah. Please could you add a line for this issue at the top of `history.adoc`? I think the format should be obvious from the existing entries. Once that is in place in your PR, we can merge it.

**Comment by bzah** [comment]
I read the issue too quickly and didn't catch that the history.adoc update was needed.
It's now done.

**Comment by JonathanGregory** [comment]
Thanks, @bzah and @larsbarring. I will merge it now.
