### ISSUE TITLE
Incorrect formating for some `<=` in Appendix D  

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/cf-conventions#472]
# Incorrect formating for some `<=` in Appendix D  
# Moderator

# Requirement Summary
Asciidoctor turns a plain `<=` into an arrow, so these instances need protecting  with `\<=`. For example, see http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#_ocean_s_coordinate_generic_form_1.

There is a useful comment in `appf.adoc` relating to this:
```
// The following lines shows how to insert Unicode for <=.  A plain '<=' turns into an arrow.
// Except as marked, all work for asciidoctor and none work for asciidoctor-pdf.
//     **`-90.0 &#x2264; latitude_of_projection_origin &#x2264; 90.0`** +
//doesn't work for asciidoctor     **`-90.0 &#2264; latitude_of_projection_origin &#2264; 90.0`** +
//     **`-90.0 &le; latitude_of_projection_origin &le; 90.0`** +
//     **`-90.0 &leq; latitude_of_projection_origin &leq; 90.0`** +
//     **`-90.0 +++<u>&le;</u>+++ latitude_of_projection_origin +++<u>&le;</u>+++ 90.0`** +
//     **`-90.0 < = latitude_of_projection_origin < = 90.0`** +
//     **`-90.0 \<= latitude_of_projection_origin \<= 90.0`** +
// The cleanest-looking, which sometimes works for asciidoctor-pdf:
     **`-90.0 \<= latitude_of_projection_origin \<= 90.0`**
```

# Technical Proposal Summary
Change occurrences of `<=` to `\<=`.
# Benefits
The affected mathematical relationships will no longer be ambiguous. 
# Status Quo
The affected mathematical relationships are ambiguous. 
# Associated pull request
#473

**Comment by larsbarring** [comment]
I reviewed the changes and it looks good. As this PR is correcting a typographical problem within the system and how it renders specific character combination (not even a "typo") it can perhaps be merged immediately?

**Comment by davidhassell** [comment]
I would have thought so, too. Thanks, Lars. Merging now.
