### ISSUE TITLE
Simple correction to Example 6.1.2

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/cf-conventions#490]
I have just come across a suggested correction in PR https://github.com/cf-convention/cf-convention.github.io/pull/216 by @Fred-Leclercq. Basically he notes that in the example the standard name does not exists and suggests an alternative, i.e. the following change:
> ~~abundance:standard_name = "number_concentration_of_organisms_in_taxon_in_sea_water" ;~~
> abundance:standard_name = "number_concentration_of_biological_taxon_in_sea_water" ;

As I have no insight into this subject area, could some else have a look? Moreover, it might be easier to create a new PR using the current draft (and then in this repo) rather than trying to update the current one in the other repo.

ping @JonathanGregory (as you might know yourself, or know who has the right expertise)

**Comment by JonathanGregory** [comment]
I agree. Thanks, both.

**Comment by larsbarring** [comment]
OK, I will prepare a PR.

**Comment by larsbarring** [comment]
Hi David @davidhassell I put you as reviewer of the PR. As the PR takes care of a simple correction I suggest that it can be merged ass soon as it is accepted.

**Comment by larsbarring** [comment]
Closed as comkpleted via PR #492
