### ISSUE TITLE
corrections to `units_metadata` text

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-conventions#496]
I've just read through the `units_metadata` text that was implemented today by PR #480 in the rendered versions, and noticed:

* An omission which is so silly that it's funny, namely that I forgot to add the new `units_metadata` attribute to Appendix A. :smile: My proposed text is "Specifies the interpretation (on-scale, difference or unknown) of the unit of temperature appearing in the **`units`** attribute."
* Some **bolding** which was included for clarity during the discussion and should have been removed.

I have prepared corrections for these in PR #495, and taken advantage of the opportunity to clarify the words in one place ("for guidance _only_ regarding `temperature: unknown`, _not_ as a CF convention") and to insert a missing comma.

Please could someone check and merge?

**Comment by davidhassell** [comment]
Caught just in time - many thanks, Jonathan! It looks fine to me - merging.
