### ISSUE TITLE
Formatting of local links in text; Lists of Figures, Tables and Examples

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/cf-conventions#499]
# Formatting of local links in text; Lists of Figures, Tables and Examples
# Moderator
*not yet*
# Requirement Summary
Currently there are some formatting deficiences in local links that affects the Lists of Tables, Figures, and Examples. These need to be fixed and preferably harmonised so that the three Lists have a similar style.

# Technical Proposal Summary
*  The formatting of Lists of Tables, Figures and Examples should be harmonised. In my view the List of Tables and List of Examples are good (however, see below). The List of Figures should be changed to conform to these two. This is done by changing the format of the Figure captions.
*  Several items are not included in the list of Tables and Figures because of formatting problems, cf. details below.

# Benefits
Readers will find the information as intended by the authors.

# Associated pull request
*not yet* (I do not have enough insight in asciidoc to initiate one)
# Detailed Proposal

### Tables missing in the List of Tables
*   Table 7.1
*   Table 9.1
*    Table 9.2
*    Table 9.3
*    Table 9.4
*    Table D.2
*    Table J.1
### Table caption formatting issues
 *   Table 3.1: -- which Example; 3.8?
 *   Table 3.2: -- which Example; 3.8?
 *   Table D.1: -- "Table D.1" is missing, and complex entry in the List of Tables
 *   Table D.2: -- "Table D.2" is missing
 *   Table I.1: -- complex entry in the List of Tables, -- contains malformed figure reference
 *   Table I.2: -- complex entry in the List of Tables, -- contains malformed figure references
 *   Table J.1: -- no table caption at all, is currently formatted as subsection "Common Conversions and Formulas"
### Text issues
*    Section 1.3, first sentence: -- check reference NUG for formatting (appears three times)
*    Section 1.3, "coordinate variable": -- change square brackets to parentheses in "[e.g., time(time)]"
*    4.3.1. Dimensional Vertical Coordinate, first sentence: -- does not make sense, something is missing
*    Check many references to "[NUG]" and to "[UDUNITS]" for consistency
*    Section "Bounds Tie Point Attribute and Bounds Tie Point Variable" under ch.8.3.8: -- contains malformed reference <br/>to Example 8.7 ====>>> see next point
*    Example 8.7 caption: -- contains malformed figure reference
*    Section 8.3.10 -- table contains double "[[" and "]]"
*    Appx. F, Polar Stereographic: -- internal link to Snyder not active

**Comment by JonathanGregory** [comment]
Dear @larsbarring 

Thanks a lot for this careful investigation. I certainly agree that these defects should be fixed, and also that the list of figures would more useful if it contained the fig titles too. Perhaps like you, I find the asciidoc syntax rather opaque when it gets beyond obvious text formatting.

Best wishes

Jonathan

**Comment by davidhassell** [comment]
I have prepared PR #499 that I think corrects all of these defects. I believe that all of these changes are purely editorial and do not change the meaning or interpretation of the text. Here is the HTML (gzipped) with the changes: 
[cf-conventions.html.gz](https://github.com/user-attachments/files/17723150/cf-conventions.html.gz)

@larsbarring or @JonathanGregory - could you have a glance over this, perhaps?

Many thanks,
David

**Comment by DocOtak** [comment]
@davidhassell if that 1px image is no longer necessary, usual git practice would be to delete it and retrieve it from the git history if it ever needs to be used again.

**Comment by davidhassell** [comment]
Hi @DocOtak  - sure thing. It has been deleted. I thought the comment on the procedure was potentially useful to retain but no one's going to find it there, so I'll delete that too :)

**Comment by JonathanGregory** [comment]
Dear @davidhassell

Thanks for this great effort! In looking through the PR, I've noted three places where perhaps we could have just `<<NUG>>`. I also made comments, and then resolved them, because of what looked like double refs to the tables in Sect 9, but it's correct in the HTML, so you must have the right incantation there.

Since you're on a roll, please could you also correct the first two entries in the Table of Figures, which currently appear like this?
 
> 7.1. figure 1
> 7.2. figure 2

Best wishes

Jonathan

**Comment by DocOtak** [comment]
@davidhassell I meant the file of the image, the comment is useful and probably should stay so we know what to do when a long table title happens.

**Comment by davidhassell** [comment]
> I meant the file of the image, the comment is useful and probably should stay so we know what to do when a long table title happens.

Oh, I see :) I'll delete the file and re-instate the comment.

**Comment by davidhassell** [comment]
New rendering: [cf-conventions.html.gz](https://github.com/user-attachments/files/17748081/cf-conventions.html.gz)

**Comment by davidhassell** [comment]
@DocOtak 

> Oh, I see :) I'll delete the file and re-instate the comment.

I've decided to keep the image file after all - if we want to do this technique in the future, we're going to not want the bother of creating a new file. I've updated the comment to say that there's a file that can be used: 11d5debf5f5017a2766d7db8867aefca73351ce6

**Comment by JonathanGregory** [comment]
Thanks, David. It's a shame that asciidoc isn't as clever as $\LaTeX$.

**Comment by larsbarring** [comment]
I asked a question about that over at the asciidoc support forum.

**Comment by larsbarring** [comment]
See here for response https://asciidoctor.zulipchat.com/#narrow/channel/279642-users/topic/Figure.20autonumbering.20within.20autonumbered.20Table.20text.20.3F/near/482438967

**Comment by JonathanGregory** [comment]
Thanks for finding the answer, Lars. We must try to remember about that, since this issue will be closed. If no-one objects to any of these defects being fixed, the PR will be merged next Wednesday 4th, just in time for David to build CF 1.12.
