### ISSUE TITLE
In exceptional cases allow a standard name to be aliased into two alternatives

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/cf-conventions#509]
# In exceptional cases allow a standard name to be aliased into two alternatives
# Moderator
Not yet
# Requirement Summary
In [issue #132](https://github.com/cf-convention/cf-conventions/issues/132), and in [Trac #155](https://cfconventions.org/Data/Trac-tickets/155.html) it is noted that in a few exceptional cases a *standard name* is aliased into two alternatives. The specific cases that I have come across are:
* Table version 15 and later: **`surface_carbon_dioxide_mole_flux`** is aliased into <br>  `surface_upward_mole_flux_of_carbon_dioxide` and `surface_downward_mole_flux_of_carbon_dioxide` 
* Table version 1 -- 4: **`surface_downwelling_longwave_flux`** is aliased into <br> `surface_downwelling_longwave_flux_in_air` and `surface_downwelling_longwave_flux_in_air_assuming_clear_sky` <br> (in later version the second alias was dropped).

Currently this is not allowed according to the format specification given in Appendix B.
# Technical Proposal Summary
While the two previous issues/tickets also mentions other things, this issue specifically targets how to handle the exceptional cases where one standard name is aliased into two alternatives. The required changes has already been identified in #132, and there was support from several persons, see [here](https://github.com/cf-convention/cf-conventions/issues/132#issuecomment-1881930203), [here](https://github.com/cf-convention/cf-conventions/issues/132#issuecomment-1883156801), and  [here](https://github.com/cf-convention/cf-conventions/issues/132#issuecomment-1883174326). 

Only a small change is required in Appendix B. This will be given in the associated PR. In addition, a small change is needed to the xml schema file, cf. [.io/#459](https://github.com/cf-convention/cf-convention.github.io/issues/459) where these matters will be handled.
# Associated pull request
#510

**Comment by JonathanGregory** [comment]
Thank you. @larsbarring. I support this change and the PR looks fine to me.

**Comment by larsbarring** [comment]
I should add that I have tested this change of format with the **`xsltproc`** utility for transforming the *xml* file to the corresponding *html* file that is published on the website. It worked directly without any problems at all.

**Comment by davidhassell** [comment]
Thanks, Lars. The PR looks to me, too.

**Comment by larsbarring** [comment]
Thanks David -- may I ask you to merge?

**Comment by davidhassell** [comment]
With pleasure .. I'll just wait until the 15th March to give it the full 3 weeks :)

**Comment by japamment** [comment]
@larsbarring @davidhassell,

 I see that the PR is ready to merge (and seems to have passed it's 3 week milestone on 15th March?). I am adding a comment now to record my support for the changes proposed here.
