### ISSUE TITLE
Specify publisher in the `zenodo.json` file

### ISSUE THREAD

**Issue by ethanrd** [cf-convention/cf-conventions#558]
The default publisher in the Zenodo DOI metadata is "Zenodo". It was updated to "CF Community" in the CF 1.11 DOI metadata. The publisher should be specified in the `zenodo.json` file.

I have not been able to find any details on how to specify publisher in the `zenodo.json` file.

**Comment by cofinoa** [comment]
@ethanrd I'm closing this issue in favor of #513

BTW, the metadata field for setting the publisher in Zenodo is `imprint_publisher`.
