### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by rhattersley** [cf-convention/cf-conventions#57]
Move this repo to the @cf-convention organisation.

Will require someone with **admin** rights in the @cf-convention organisation to be set up with admin rights to this repo. (Or vice versa.)

@mattben - you're the only visible member of @cf-convention - are you the right person for this job?

**Comment by mattben** [comment]
I can transfer the repo or I can fork it

**Comment by rhattersley** [comment]
I think a transfer would be best. Now that we've sorted out the asciidoc sources and agreed the outline of a way to take things from here there's very little need for the @cf-metadata organisation to remain.

There are some tweaks that will be needed to the secure tokens & travis-ci build script after the transfer, but they're pretty straightforward.

**Comment by rhattersley** [comment]
> There are some tweaks that will be needed to the secure tokens & travis-ci build script after the transfer, but they're pretty straightforward.

I've done some of the tweaks in #58, but the secure tokens will still need updating.

**Comment by rhattersley** [comment]
> I can transfer the repo or I can fork it

@mattben - can I tempt you to do the transfer?

**Comment by mattben** [comment]
I'm still confused, do you want me to transfer a repo from cf-metadata to cf-conventions or a repo from cf-conventinos to cf-metadata.

**Comment by rhattersley** [comment]
The idea is to transfer this repo to the @cf-convention organisation.

cc @JonathanGregory

**Comment by JonathanGregory** [comment]
Yes please, I agree with Richard

**Comment by mattben** [comment]
@rhattersley @JonathanGregory Done. Maybe change the description, sorry for the delay.

**Comment by rhattersley** [comment]
> Done.

Thanks @mattben - that's great news! :smile: 

@JonathanGregory - NB. Now that the repo has moved, the auto-build versions of the conventions are available at:
 - http://cfconventions.org/cf-conventions/
 - http://cfconventions.org/cf-conventions/v1.6.0/

> Maybe change the description

As things stand I don't have GitHub permissions to do that - it's not my repo any more. :wink:

I'm not exactly sure who needs to be set up with what permissions, but presumably at least @JonathanGregory should have admin on this repo?
