### ISSUE TITLE
Clean up the `gh-pages` branch

### ISSUE THREAD

**Issue by cofinoa** [cf-convention/cf-conventions#571]
The `gh-pages` branch (https://cfconventions.org/cf-conventions/) is used to upload artifacts for branch pushes, tags and releases events, providing previews. Over time, unnecessary files and images have accumulated, which are not needed for preview purposes.

#### **Proposal**
- Audit the branch to identify and remove unused or redundant files.
- Retain only the essential artifacts required for previews.
- Update workflows to prevent unnecessary files from being added in the future.

#### **Outcome**
A streamlined `gh-pages` branch with minimal clutter, reducing repository size and improving maintainability.

**Comment by JonathanGregory** [comment]
Thank you very much, Antonio @cofinoa.
