### ISSUE TITLE
change order of additional authors

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-conventions#573]
In [discussion 326](https://github.com/orgs/cf-convention/discussions/326#discussioncomment-11453055) Antonio @cofinoa has noticed that Jon Blower was inserted at the wrong point in the list of additional authors in version 1.7. In PR #572 I have corrected the order. I hope that there are no objections to merging this tomorrow so that we can include it in CF 1.12.

**Comment by davidhassell** [comment]
Thanks, Jonathan. No objections from me, and the PR looks fine. Happy to merge it tomorrow morning.
