### ISSUE TITLE
first changes for version 1.7

### ISSUE THREAD

**Issue by painter1** [cf-convention/cf-conventions#59]
These Trac tickets have been implemented for the DocBook version of the CF Conventions version 1.7.  They need to be re-implemented in the AsciiDoc version.
 ticket 61
 ticket 62 
 ticket 64
 ticket 65
 ticket 69 
For these tickets, there is no need to make corresponding changes in the conformance document.

**Comment by JonathanGregory** [comment]
Dear Jeff

Ticket 62 says was included in CF 1.6 so it should be in the AsciiDoc source of 1.6 already. You closed it after having noticed it was already implemented in 1.6. So we should not have to do that one again. I agree that the others need to be done, and that they do not require changes to the conformance document. Ticket 69 (and also ticket 80) refer to some documents on the trac wiki. It would be helpful if we could give them a more permanent status and safety as reference material. Could they be copied to github and put on the website, with new URLs, perhaps?

Best wishes

Jonathan

**Comment by painter1** [comment]
re ticket 69:  I agree that we need something better than the wiki.  In fact, the wiki links in Trac Ticket 69 are dead.  I can only find the attachments, http://cf-trac.llnl.gov/trac/attachment/wiki/Cf2CrsWkt/.  I'll look for backups.

**Comment by painter1** [comment]
re wiki links in Trac Ticket 69:  the only problem is that they were https; the server only supports http.  I added a note to the ticket.

**Comment by painter1** [comment]
I have made all the changes required to bring the Asciidoc version up to the level of the DocBook version, i.e. the 1.7 draft.  As Jonathan pointed out, ticket 62 had already been done for version 1.6.  And also I re-implemented the changes for ticket 93, which had been done in the DocBook version.

All these changes are in a branch named 1.7.1.

We still have to copy the Cf2CrsWkt wiki entry, including attachments, to a location which looks more permanent.  After updating the url which now points to the wiki, I plan to issue a pull request to merge this branch, 1.7.1, into the master branch.  Once it is approved, I will close the Trac tickets.

**Comment by rhattersley** [comment]
> All these changes are in a branch named 1.7.1.

Hi @painter1. Thanks for getting started on the changes already.

> After updating the url which now points to the wiki, I plan to issue a pull request to merge this branch, 1.7.1, into the master branch.

I strongly recommend working in a [fork](https://guides.github.com/activities/forking/) of this repository and only submitting changes via pull requests. This is the standard way of working for collaborative Open Source projects on GitHub. By working in your own fork it helps keep the "official" state of play more obvious (and reduces the chance of confusing the automated build script).

I'd also recommend [protecting](https://help.github.com/articles/about-protected-branches/) the `master` branch.

**Comment by painter1** [comment]
Thanks for the workflow advice.  As I said in the email thread "CF 1.6 from AsciiDoc", I'll work off a personal fork in the future; that was a good idea.  Also thanks for recommending that I protect the master branch; it's done now.
