### ISSUE TITLE
Re-enable automatic HTML/PDF builds

### ISSUE THREAD

**Issue by rhattersley** [cf-convention/cf-conventions#61]
The `secure` values in [.travis.yml](https://github.com/cf-convention/cf-conventions/blob/master/.travis.yml) need updating to work in the new location.

The three values are:

* `GH_TOKEN`: Defines a [personal access token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) to authenticate against this repo. This needs to be an access token for a user with write access to this repo.
* `GIT_EMAIL` & `GIT_NAME`: Defines the git identity used for the automated commits. Should perhaps be set to something like "auto@cf-conventions" and "auto-generated".

**Comment by rhattersley** [comment]
I suggest we create a [robot account](https://help.github.com/articles/what-s-the-difference-between-user-and-organization-accounts/#personal-user-accounts) so we can avoid collateral damage should someone ever leak the access token. @rsignell-usgs / @ocefpaf - have you any experience with using a bot account?

**Comment by ocefpaf** [comment]
I never used one but I am :+1: to the idea.

**Comment by rhattersley** [comment]
Behold @cf-conventions-bot!

**Comment by ocefpaf** [comment]
Loved the icon!

**Comment by rhattersley** [comment]
Thank you! I feel like a proud father. :wink:

**Comment by rhattersley** [comment]
@mattben or @rsignell-usgs - if you're happy to give @cf-conventions-bot write access to this repo I can get the automated builds working again.

**Comment by rhattersley** [comment]
> @mattben or @rsignell-usgs - if you're happy to give @cf-conventions-bot write access to this repo I can get the automated builds working again.

Pretty please!? :bowtie:

I'd *love* to get some of the open pull requests merged, but before I start asking for help with that I think we need to get the automated builds working.

**Comment by mattben** [comment]
I've added the bot which generated a organization invitation as well.

**Comment by rhattersley** [comment]
> I've added the bot which generated a organization invitation as well.

Thanks @mattben. :+1: :smile:

**Comment by rhattersley** [comment]
> mattben closed this 27 minutes ago

@mattben - please could you re-open this issue - the automatic builds won't be working until I get a PR merged which updates the encrypted values in `.travis.yml`.

**Comment by mattben** [comment]
opps my bad

**Comment by rhattersley** [comment]
> opps my bad

No problemo - thanks! :smile:
