### ISSUE TITLE
Typo in original "4.2. Longitude Coordinate"

### ISSUE THREAD

**Issue by rhattersley** [cf-convention/cf-conventions#8]
See http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#longitude-coordinate

It includes the text:

> The units `attribute` will be a string

Note how it is the word "attribute" that has been highlighted, instead of "units" as expected and as done in section 4.1, "Latitude Coordinate".

Should we fix this, or honour the original?

**Comment by rhattersley** [comment]
I'm inclined to agree with the stance [suggested](https://github.com/cf-metadata/cf-conventions/issues/13#issuecomment-132254834) by @davidhassell - i.e. match whatever is in 1.6. I'm going to defer this to v1.7.

**Comment by dblodgett-usgs** [comment]
Fixed? Hopefully since it was the 1.7 milestone?
